Repository EbookFoundation/free-programming-books, pull requests merged in 2020-11, with the labels that each got.

#4942 Added 5 Arduino books.
  free-programming-books.md
Labels: resubmit PR

#4908 Added Python tutorial at Tutorialspoint
  free-programming-books.md
  free-programming-interactive-tutorials-en.md
Labels: question

#4945 Added a Visual Basic book.
  free-programming-books.md
Labels: resubmit PR

#4975 Added C언어 코딩도장 as course in C/C++ section (RESTORED REMOVED ADDITIONS)
  free-courses-ko.md
Labels: resubmit PR

#4991 Add Java books
  free-programming-books-tr.md
Labels: linter failure, resubmit PR

#3642 Add two new books: React and Scratch
  free-programming-books-es.md
Labels: conflicts, resubmit PR

#4906 add some golang books in spanish
  free-programming-books-es.md
Labels: resubmit PR

#5034 Update podcast in Spanish
  free-podcasts-screencasts-es.md
Labels: resubmit PR

#5041 Added 10 courses on Android
  free-courses-en.md
Labels: resubmit PR

#4997 Adds the 'Nuxt.js Fundamentals' course.
  free-courses-en.md
Labels: conflicts

#4995 Adds 'Vue.js Components Fundamentals' course.
  free-courses-en.md
Labels: conflicts

#5042 Update free-courses-hi.md
  free-courses-hi.md
Labels: resubmit PR

#4996 Adds the 'JavaScript Testing Fundamentals' course
  free-courses-en.md
Labels: conflicts, please resubmit PR

#5061 Add resources to free-programming-books-ja.md
  free-programming-books-ja.md
Labels: please resubmit PR

#5070 Add The Rust Programming Language, check_urls=free-programming-books-ko.md
  free-programming-books-ko.md
Labels: please resubmit PR

#5072 Add and fix CP resources, check_urls=problem-sets-competitive-program…
  problem-sets-competitive-programming.md
Labels: please resubmit PR

#4967 #4966 Add new JS tutorial
  free-courses-en.md
Labels: please resubmit PR

#4872 Added Web Almanac
  free-programming-books.md
Labels: please resubmit PR

#3876 Adding Java Desktop by Ifnu Bima
  free-programming-books-id.md
Labels: linter error

#3907 Added Git/Github book
  free-programming-books.md
Labels: linter error

#3961 added more links to information security
  problem-sets-competitive-programming.md
Labels: linter error

#4255 Add Stanford's cs330 to deep learning list
  free-courses-en.md
Labels: please resubmit PR

#5096 Add Chewing C, C++, check_urls=free-programming-books-ko.md
  free-courses-ko.md
  free-programming-books-ko.md
Labels: question

#4392 Dart official Codelabs Added
  free-programming-interactive-tutorials-en.md
Labels: help wanted, please resubmit PR

#4675 Add a Node.js Programming Language Course
  free-courses-id.md
Labels: conflicts

#4890 Added free CodeIgniter course, and organizing list by sub-categories
  free-courses-pt_BR.md
Labels: linter error

#4943 Including cheatsheet for python
  free-programming-cheatsheets.md
Labels: linter error

#4926 add free ebook java spring boot written in Bahasa Indonesia
  free-programming-books-id.md
Labels: please resubmit PR

#4320 Added greek programming books and removed an SQL book with dead link
  free-programming-books-gr.md
Labels: linter error

#4412 Updated free-programming-books.md with DBMS books
  free-programming-books.md
Labels: please resubmit PR

#4874 Add Single page apps in depth by Mixu
  free-programming-books.md
Labels: linter error, please resubmit PR

#5011 added Python cheat sheets
  free-programming-cheatsheets.md
Labels: linter error

#4818 Add iOS Development Bootcamp
  free-courses-en.md
Labels: conflicts, linter error

#4326 Added a pdf book on fortran by Clive G. Page. The book has tons of programing topics a…
  free-programming-books.md
Labels: linter error

#3938 Adding courses content
  free-courses-en.md
Labels: linter error

#4177 Added a while new editions of cources in english and removed some failed links.
  free-courses-en.md
Labels: conflicts

#3977 Add Bahasa Indonesia book c# resource
  free-programming-books-id.md
Labels: linter error

#3993 Updating ptBR courses
  free-courses-pt_BR.md
Labels: linter error

#4763 Added bengali cheatsheet link from the devsonket team.
  free-programming-books-bl.md
Labels: please resubmit PR

#4230 Standardize wikibooks
  free-programming-books-pl.md
  free-programming-books-se.md
Labels: conflicts

#4958 add todos curso do Curso em vídeo sobre python
  free-courses-pt_BR.md
Labels: linter error, please resubmit PR

#5009 Add Free and Open Machine Learning book to free-programming-books.md
  free-programming-books.md
Labels: please resubmit PR

#4742 Add Google Kickstart to problem-sets-competitive-programming.md
  problem-sets-competitive-programming.md
Labels: discussion, linter error

#4944 Cheatsheet revision
  free-programming-books.md
  free-programming-cheatsheets.md
Labels: conflicts, please resubmit PR

#4932 Translate headings in free-courses-ru.md
  free-courses-ru.md
Labels: conflicts, please resubmit PR

#4954 add curso de python PT-br
  free-courses-pt_BR.md
Labels: linter error, please resubmit PR

#5175 Updated Turkish podcast/screencast list
  free-podcasts-screencasts-tr.md
Labels: conflicts

#5071 Agregando The Dojo MX Screencast
  free-podcasts-screencasts-es.md
Labels: please resubmit PR

#4985 Add Algorithm books to TR booklist
  free-programming-books-tr.md
Labels: conflicts, linter error, please resubmit PR
