Repository EbookFoundation/free-programming-books, pull requests merged in 2020-10, with the labels that each got.

#3945 Add CodeIgniter Free Courses at free-courses-id.md
  free-courses-id.md
Labels: resubmit PR

#3959 Update free-programming-books.md
  free-programming-books.md
Labels: resubmit PR

#3968 Added three books by Prakash B Hegade
  free-programming-books.md
Labels: resubmit PR

#3980 Added OpenCV Course by NgodingPython
  free-courses-id.md
Labels: resubmit PR

#3889 Add Docker and Kubernetes courses and adjust sub headings
  free-courses-en.md
Labels: conflicts

#4016 Add Course CRUD Node.js
  free-courses-pt_BR.md
Labels: resubmit PR

#3999 Added JavaScript Podcast
  free-podcasts-screencasts-en.md
Labels: resubmit PR

#3837 edit: clean out broken pl links
  free-programming-books-pl.md
Labels: PR requested

#3995 Added free e-book reference
  free-programming-books.md
Labels: resubmit PR

#4017 Update spanish books
  free-programming-books-es.md
Labels: resubmit PR

#4045 Added The Vue.js Handbook to Vue links
  free-programming-books.md
Labels: resubmit PR

#4053 Add React Native Category and 2 courses
  free-courses-pt_BR.md
Labels: resubmit PR

#3843 Add Book React Native Notes for Professionals
  free-programming-books.md
Labels: linter failure

#3982 Added books in Algorithms and Competitive Programming
  free-programming-books.md
Labels: resubmit PR

#3985 Good resources to learn capture the flags competitions - Cybersecurity+Linux
  problem-sets-competitive-programming.md
Labels: resubmit PR

#4041 Add python di prograte course in bahasa
  free-courses-id.md
Labels: resubmit PR

#4141 Added React Podcast
  free-podcasts-screencasts-en.md
Labels: resubmit PR

#4106 add materials about swift
  free-programming-books-ru.md
  problem-sets-competitive-programming.md
Labels: resubmit PR

#4110 Update The Art of Assembly Language
  free-programming-books.md
Labels: resubmit PR

#4136 Updated code of conduct
  CODE_OF_CONDUCT.md
Labels: resubmit PR

#4117 Created HOWTO-zh.md
  HOWTO-zh.md
Labels: resubmit PR

#3872 Added ANSI C books
  free-programming-books-bg.md
Labels: linter failure

#4200 create HOWTO-hi.md
  HOWTO-hi.md
Labels: resubmit PR

#4223 Added books.
  free-programming-books-ta.md
  free-programming-books.md
Labels: resubmit PR

#4224 Add Course(s) & Book(s)
  free-courses-id.md
  free-programming-books-id.md
Labels: resubmit PR

#4264 feat: translate CONTRIBUTING doc into zh-TW version
  CONTRIBUTING-zh-TW.md
  CONTRIBUTING-zh.md
  CONTRIBUTING.md
Labels: resubmit PR

#4310 Learn Ruby
  free-courses-en.md
Labels: conflicts

#4270 added new free course for database management
  free-courses-en.md
Labels: question

#4304 Added Laravel, Bootstrap into free-programming-books-zh.md
  free-programming-books-zh.md
Labels: resubmit PR

#4261 Add TH language books
  README.md
  free-programming-books-th.md
Labels: resubmit PR

#4325 Added assembly books.
  free-programming-books.md
Labels: discussion, resubmit PR

#4293 Translate HOWTO.md to Brazilian Portuguese
  HOWTO-hi.md
  HOWTO-zh-TW.md
  HOWTO-zh.md
  HOWTO.md
  HOWTO.pt_BR.md
Labels: resubmit PR

#4309 Added Reading Materials and Videos of Python for Everybody - Coursera
  free-courses-en.md
Labels: question

#4354 Adding Git & Github tutorial to the English (screencast)
  free-podcasts-screencasts-en.md
Labels: duplicate, resubmit PR

#4356 Added git playground link
  free-programming-playgrounds.md
Labels: conflicts

#4363 Added one course link
  free-courses-en.md
Labels: resubmit PR

#4387 Added free Russian programming books for React
  free-programming-books-ru.md
Labels: not_free?

#4390 added courses
  free-courses-en.md
Labels: conflicts

#4394 Update free-courses-pt_BR.md
  free-courses-pt_BR.md
Labels: resubmit PR

#4395 Update free-courses-en.md
  free-courses-en.md
Labels: resubmit PR

#4404 Adding a Course
  free-courses-pt_BR.md
Labels: resubmit PR

#4410 Add "Frontend Weekend" podcast
  free-podcasts-screencasts-ru.md
Labels: question

#4430 Added 4 German Courses
  free-courses-de.md
Labels: resubmit PR

#4415 Added Math for Machine Learning by Marc Peter Deisenroth
  free-programming-books.md
Labels: question

#4431 Added data structure course by mycodeschool
  free-courses-en.md
Labels: resubmit PR

#4435 Add How to Program with Java Podcast
  free-podcasts-screencasts-en.md
Labels: conflicts

#4274 Update free-courses-id.md
  free-courses-id.md
Labels: resubmit PR

#4298 Added python and HTML/CSS course links for beginners as part of hacktoberfest2020 (PR resubmission)
  free-courses-en.md
Labels: resubmit PR

#4302 Add Books from Flavio Copes and Courses from Dicoding Indonesia
  free-courses-id.md
Labels: resubmit PR

#4407 Add: Beginner's Series to: JavaScript & Beginner's Series to: Node.js
  free-courses-en.md
Labels: resubmit PR

#4483 Add Runestone Interactive Python Guide
  free-programming-interactive-tutorials-en.md
Labels: resubmit PR

#4513 Add UA courses file with two Python courses
  README.md
  free-courses-ua.md
Labels: resubmit PR

#4484 Add tutorial rails girls
  free-courses-pt_BR.md
Labels: resubmit PR

#4494 Update free-courses-hi.md
  free-courses-hi.md
Labels: resubmit PR

#4508 Add links to erlang resources for italian section
  free-courses-it.md
Labels: resubmit PR

#4512 Added new book check_urls=free-programming-books-de.md
  free-programming-books-de.md
Labels: resubmit PR

#4522 Kotlin tutorials resource added
  free-programming-interactive-tutorials-en.md
Labels: resubmit PR

#4195 Added ASP.NET Core course in Web Development
  free-courses-en.md
Labels: resubmit PR

#4510 Added new resource and fixed and arranged index and resources alphabetically. [Hacktober Fest]
  free-courses-en.md
  free-courses-hi.md
Labels: conflicts, resubmit PR

#4534 Added Python and Java Playground
  free-programming-playgrounds.md
Labels: resubmit PR

#4535 Added CS book
  free-programming-books.md
Labels: resubmit PR

#4571 Add MongoDB cheatsheet
  free-programming-cheatsheets.md
Labels: conflicts

#4556 Added Book MySQL
  free-programming-books-id.md
Labels: resubmit PR

#4608 Add Web Programming Course from Harvard.
  free-courses-en.md
Labels: resubmit PR

#4545 Adding a MATLAB book
  free-programming-books.md
Labels: resubmit PR

#4597 Add math foundations computing book
  free-programming-books-pt_BR.md
Labels: resubmit PR

#4599 Add algorithms course by Harvard
  free-courses-en.md
Labels: question

#4623 Added Ruby Online Playground
  free-programming-books-fa_IR.md
  free-programming-playgrounds.md
Labels: resubmit PR

#4625 Added javascript data structures and algorithms
  free-programming-interactive-tutorials-en.md
Labels: resubmit PR

#4657 Update free-programming-books.md
  free-programming-books.md
Labels: resubmit PR

#4340 Add Processing Resource - Fix
  free-courses-en.md
Labels: resubmit PR

#4600 add android course track by harvard
  free-courses-en.md
Labels: resubmit PR

#4601 Add game Course from Harvard
  free-courses-en.md
Labels: resubmit PR

#4602 Add iOS Course from Harvard
  free-courses-en.md
Labels: resubmit PR

#4628 Create free-courses file for Persian
  README.md
  free-courses-fa_IR.md
  free-programming-books-fa_IR.md
Labels: conflicts, resubmit PR

#4647 Updated free-programming-interactive-tutorials-en.md
  free-programming-interactive-tutorials-en.md
Labels: conflicts

#4649 Update free-programming-interactive-tutorials-en.md
  free-programming-interactive-tutorials-en.md
Labels: resubmit PR

#4653 Add Ruby book in Tamil, check_urls=free-programming-books-ta.md
  free-programming-books-ta.md
Labels: resubmit PR

#4667 Create free-courses-tr.md
  README.md
  free-courses-tr.md
Labels: resubmit PR

#4672 add a new reinforcement learning book
  free-programming-books-ja.md
Labels: resubmit PR

#4691 java book for beginners
  free-programming-books-pt_BR.md
Labels: resubmit PR

#4693 Add Docker courses from #3856 issue, check_urls=free-courses-en.md
  free-courses-en.md
Labels: resubmit PR

#4702 Fix the rest of the devopscollective books
  free-programming-books.md
Labels: conflicts

#4708 Update free-programming-books-pt_BR.md
  free-programming-books-pt_BR.md
Labels: conflicts

#4721 Adding section and a book for Blazor Framework
  free-programming-books.md
Labels: question

#4695 Add DenoJS section and a free Deno Beginner Course
  free-courses-en.md
Labels: resubmit PR

#4724 add free programming and algorithms pt-br book
  free-programming-books-pt_BR.md
Labels: resubmit PR

#4727 add free arduino and raspberry pi courses pt_PT
  README.md
  free-courses-pt_PT.md
Labels: resubmit PR

#4729 [Kotlin] Add Content (screencast, courses)
  free-courses-en.md
  free-podcasts-screencasts-en.md
Labels: resubmit PR

#4739 Create CONTRIBUTING-fa_IR.md
  CONTRIBUTING-fa_IR.md
  CONTRIBUTING-zh-TW.md
  CONTRIBUTING-zh.md
  CONTRIBUTING.md
Labels: resubmit PR

#4741 Update free-programming-books.md
  free-programming-books.md
Labels: question

#4751 Update free-courses-en.md
  free-courses-en.md
Labels: resubmit PR

#4752 free-programming-cheatsheets.md
  free-programming-cheatsheets.md
Labels: resubmit PR

#4756 Added Flask Documentation book.
  free-programming-books.md
Labels: resubmit PR

#4761 Added Electron.js to free-programming-books-zh
  free-programming-books-zh.md
Labels: resubmit PR

#4764 Added design pattern link in language agnostic section
  free-programming-books.md
Labels: resubmit PR

#4767 Added cheat sheet refence to swift and c#
  free-programming-cheatsheets.md
Labels: resubmit PR

#4769 add: Deno tutorial
  free-programming-books-zh.md
Labels: conflicts

#4772 Add "Introduction to Reinforcement Learning"
  free-courses-en.md
Labels: resubmit PR

#4766 Create free-courses-fr.md
  free-programming-books-fr.md
Labels: resubmit PR

#4848 Add the german translation of "A byte of Python"
  free-programming-books-de.md
Labels: resubmit PR

#4851 Add Ruby Cheat Sheet
  free-programming-cheatsheets.md
Labels: resubmit PR

#4852 Add Bash Scripting Cheatsheet
  free-programming-cheatsheets.md
Labels: linter failure

#4451 added Spring framework PDF
  free-programming-books.md
Labels: conflicts, resubmit PR

#4800 add resource Belajar Dengan Jenius Golang and fix error blank lines
  free-programming-books-id.md
Labels: question

#4813 Add Resources, Add info
  free-courses-ko.md
Labels: resubmit PR

#4856 Chore/remove broken links es
  free-programming-books-es.md
Labels: resubmit PR

#4859 Add Vulkan tutorial, check_urls=free-programming-books.md
  free-programming-books.md
Labels: resubmit PR

#4181 Clean up PR #3422 #3429 #3451 #3510
  free-courses-en.md
  free-courses-th.md
  free-podcasts-screencasts-en.md
  free-podcasts-screencasts-pt_BR.md
  free-programming-books-es.md
  free-programming-books-ja.md
Labels: resubmit PR

#4888 Adding a lot of Beej's Guides and their official translations.
  free-programming-books-de.md
  free-programming-books-fr.md
  free-programming-books-it.md
  free-programming-books-ko.md
  free-programming-books-pl.md
  free-programming-books-pt_BR.md
  free-programming-books-ru.md
  free-programming-books-tr.md
  free-programming-books-zh.md
  free-programming-books.md
Labels: resubmit PR

#4891 add pyqt books
  free-programming-books-ko.md
Labels: resubmit PR

#4895 add java free course
  free-courses-vi.md
Labels: resubmit PR

#4897 add sql course
  free-courses-vi.md
Labels: resubmit PR

#4898 Removed Duplictes/redirect links to goalkicker.com & Added few books from same
  free-programming-books.md
Labels: resubmit PR

#4900 add objective c free course
  free-courses-vi.md
Labels: resubmit PR

#4924 Added a new course Python in Pt-BR (Programação em Python - Bóson Treinamentos)
  free-courses-pt_BR.md
Labels: resubmit PR

#4962 Added credits to a graphics programming resource and removed vulkan subcategory
  free-programming-books.md
Labels: conflicts, resubmit PR

#4989 Added Descubre React book
  free-programming-books-es.md
Labels: resubmit PR
