Repository EbookFoundation/free-programming-books, pull requests merged in 2021-11, with the labels that each got.

#6543 Add "Hard Rock CoffeeScript"
  books/free-programming-books-langs.md
Labels: ready to merge

#6520 Update unavailable links and tutorial version
  books/free-programming-books-zh.md
Labels: waiting for changes

#6542 Ukrainian localization is added
  CODE_OF_CONDUCT-uk.md
  HOWTO-ar.md
  HOWTO-bs.md
  HOWTO-de.md
  HOWTO-es.md
  HOWTO-fa_IR.md
  HOWTO-fr.md
  HOWTO-hi.md
  HOWTO-id.md
  HOWTO-it.md
  HOWTO-km.md
  HOWTO-ko.md
  HOWTO-pl.md
  HOWTO-pt_BR.md
  HOWTO-ru.md
  HOWTO-sl.md
  HOWTO-sv.md
  HOWTO-uk.md
  HOWTO-vi.md
  HOWTO-zh.md
  HOWTO-zh_TW.md
  HOWTO.md
Labels: waiting for changes

#6568 Add Data Structures - Aditya CSE
  books/free-programming-books-subjects.md
Labels: ready to merge

#6412 add R ile Programlamaya Giriş ve Uygulamalar to tr
  books/free-programming-books-tr.md
Labels: ready to merge

#6465 Add CI/CD with Docker and Kubernetes Book
  books/free-programming-books-subjects.md
Labels: ready to merge

#6533 Update in online compiler
  more/free-programming-playgrounds.md
Labels: ready to merge

#6578 fix(docs)!: Ukrainian language code is `uk` not `ua`
  README.md
  books/free-programming-books-uk.md
  courses/free-courses-uk.md
Labels: ready to merge

#6541 Add Arabic courses
  courses/free-courses-ar.md
Labels: waiting for changes

#6513 Add 3 links and update 2 links
  courses/free-courses-pt_BR.md
Labels: waiting for changes

#6076 Farsi/Persian podcast
  casts/free-podcasts-screencasts-fa_IR.md
Labels: ready to merge

#6504 Translate CONTRIBUTING file to Filipino
  CONTRIBUTING-fil.md
  CONTRIBUTING.md
Labels: New Feature, ready to merge

#6438 Add HOWTO.md Translation to Filipino
  HOWTO-fil.md
  HOWTO.md
Labels: New Feature, ready to merge

#6524 Translate Code of Conduct to Filipino
  CODE_OF_CONDUCT-fil.md
Labels: New Feature, ready to merge

#6585 chore: Bump pr/ahmadsoni/patch-1: create curse C #5647
  books/free-programming-books-id.md
Labels: ready to merge

#6583 feat(books): `CI/CD for Monorepos` by SemaphoreCI
  books/free-programming-books-subjects.md
Labels: Needs Review

#6527 adding resources in free-courses-en.md
  courses/free-courses-en.md
Labels: waiting for changes

#5690 added courses on free-course-en
  courses/free-courses-en.md
Labels: waiting for changes, linter error, conflicts, stale

#5952 Agrege 2 cursos en la seccion free-course-es.md uno en sql y otro en git
  courses/free-courses-es.md
Labels: ready to merge

#5837 Added links to korean docs
  CONTRIBUTING-de.md
  CONTRIBUTING-el.md
  CONTRIBUTING-es.md
  CONTRIBUTING-fa_IR.md
  CONTRIBUTING-fil.md
  CONTRIBUTING-fr.md
  CONTRIBUTING-id.md
  CONTRIBUTING-it.md
  CONTRIBUTING-pt_BR.md
  CONTRIBUTING-ru.md
  CONTRIBUTING-vi.md
  CONTRIBUTING-zh.md
  CONTRIBUTING-zh_TW.md
  CONTRIBUTING.md
  HOWTO-ar.md
  HOWTO-el.md
  HOWTO-fil.md
  HOWTO-id.md
  HOWTO-it.md
  HOWTO-km.md
  HOWTO-pl.md
  HOWTO-sl.md
  HOWTO-sv.md
  HOWTO-th.md
  HOWTO-uk.md
  HOWTO-vi.md
  HOWTO.md
Labels: ready to merge

#6547 Added C++ fundamental book
  books/free-programming-books-langs.md
Labels: question, ready to merge

#6452 Update free-programming-books-langs.md
  books/free-programming-books-langs.md
Labels: waiting for changes

#6592 docs: update statistic counters of the repo
  README.md
Labels: ready to merge

#6540 Add course to courses\free-courses-en.md
  courses/free-courses-en.md
Labels: ready to merge

#6581 Resourses
  courses/free-courses-en.md
Labels: ready to merge

#6593 Add new iOS and Swift courses to free-courses-en.md
  courses/free-courses-en.md
Labels: ready to merge

#6181 add french c++ course
  courses/free-courses-fr.md
Labels: question, Needs Review

#6186 Added in Next.js
  books/free-programming-books-langs.md
Labels: waiting for changes

#5831 translating HOWTO.md to Dutch
  HOWTO-nl.md
Labels: New Feature, waiting for changes

#6002 add PHP courses
  courses/free-courses-en.md
Labels: waiting for changes

#5919 Added miscelaneous resource about different topics
  books/free-programming-books-es.md
Labels: question, waiting for changes

#6127 added programming podccast
  casts/free-podcasts-screencasts-fa_IR.md
Labels: waiting for changes, stale

#6594 Add tutorialspoint's git tutorial and some assembly guides
  books/free-programming-books-langs.md
Labels: ready to merge

#6595 update dead matlab link
  books/free-programming-books-sv.md
Labels: ready to merge

#5351 docs: Add Contributor Over Time graph
  HOWTO.md
Labels: New Feature, ready to merge

#6597 add polish git cheatsheet from #6008 and Allison's Vim from #6091
  more/free-programming-cheatsheets.md
Labels: ready to merge

#6596 Add Objective-C category and a course
  courses/free-courses-en.md
Labels: waiting for changes

#6492 Add Let's Data Podcast on Podcasts pt_BR
  casts/free-podcasts-screencasts-pt_BR.md
Labels: question, waiting for changes

#6557 Update free-courses-pt_BR.md
  courses/free-courses-pt_BR.md
Labels: waiting for changes, linter error

#6573 Added "Learning the elixir language" ebook
  books/free-programming-books-langs.md
Labels: waiting for changes

#6344 Add Pythontutor & Yandex C++ courses to the list of Russian coursers
  courses/free-courses-ru.md
Labels: ready to merge

#6079 add react js into js section
  books/free-programming-books-fa_IR.md
Labels: ready to merge, stale

#6115 Add web development and python course (Farsi/Persian)
  courses/free-courses-fa_IR.md
Labels: ready to merge, stale

#6154 Add malas ngoding's indonesian laravel course
  courses/free-courses-id.md
Labels: ready to merge, stale

#6471 docs(free-programming-books-subjects): fixed broken links #5470
  books/free-programming-books-subjects.md
Labels: waiting for changes

#6238 Added node js course in english
  courses/free-courses-en.md
Labels: waiting for changes, stale

#6214 Inspect element free course added
  courses/free-courses-fa_IR.md
Labels: waiting for changes, conflicts, stale

#6450 Added Python , Django , DRF , GitHub with Visual Studio & React JS in Hindi.
  courses/free-courses-hi.md
Labels: waiting for changes, linter error, conflicts

#6460 Aprendejavascript added (spanish language)
  courses/free-courses-es.md
Labels: waiting for changes, linter error

#6449 Added Exploring Modern Fortran Basics
  books/free-programming-books-langs.md
  books/free-programming-books-subjects.md
Labels: question, waiting for changes, linter error

#6600 Add some hebrew podcasts
  README.md
  casts/free-podcasts-screencasts-he.md
Labels: question

#6429 Added Bengali Language Support for HOWTO
  HOWTO-ar.md
  HOWTO-bn.md
  HOWTO-bs.md
  HOWTO-de.md
  HOWTO-es.md
  HOWTO-fa_IR.md
  HOWTO-fr.md
  HOWTO-hi.md
  HOWTO-id.md
  HOWTO-it.md
  HOWTO-km.md
  HOWTO-ko.md
  HOWTO-pl.md
  HOWTO-pt_BR.md
  HOWTO-ru.md
  HOWTO-sl.md
  HOWTO-sv.md
  HOWTO-vi.md
  HOWTO-zh.md
  HOWTO-zh_TW.md
  HOWTO.md
Labels: New Feature, waiting for changes

#6340 Added freeCodeCamp courses
  more/free-programming-interactive-tutorials-en.md
Labels: question, ready to merge

#6426 Update free-programming-books-ar.md
  books/free-programming-books-ar.md
Labels: linter error, ready to merge

#6604 fix(books): update Micro Focus Object COBOL broken url
  books/free-programming-books-langs.md
Labels: ready to merge

#6607 Add "Squeak by Example"
  books/free-programming-books-langs.md
Labels: ready to merge

#6608 Fix "Le langage Caml"
  books/free-programming-books-fr.md
Labels: ready to merge

#6610 Add "Développement d'applications avec Objective Caml"
  books/free-programming-books-fr.md
Labels: ready to merge

#6612 Remove "Professional Assembly Language"
  books/free-programming-books-langs.md
Labels: ready to merge

#6567 docs: Add HOWTO in Turkish
  HOWTO-tr.md
Labels: New Feature, waiting for changes

#6603 Add "Scheme 9 from Empty Space"
  books/free-programming-books-langs.md
Labels: waiting for changes

#6187 add indonesia course for express js + podcast
  casts/free-podcasts-screencasts-id.md
  courses/free-courses-id.md
Labels: waiting for changes, stale

#6560 Added some spark tutorials
  courses/free-courses-en.md
Labels: waiting for changes, linter error

#6490 Added a new section - Machine Learning for Podcasts
  casts/free-podcasts-screencasts-en.md
Labels: waiting for changes

#6313 add react course & tutorial
  courses/free-courses-id.md
Labels: waiting for changes, linter error, stale

#6606 Sqlite: add course
  books/free-programming-books-langs.md
Labels: question, waiting for changes, discussion

#6624 Add Courses and Interactive tutorials (RU)
  courses/free-courses-ru.md
Labels: ready to merge

#6621 Fixed Markdown In Bangla Books List
  books/free-programming-books-bn.md
Labels: ready to merge

#6628 add trypython.jcubic.pl
  more/free-programming-playgrounds.md
Labels: ready to merge

#6618 chore: complete review of #6567 HOWTO in Turkish
  docs/HOWTO-tr.md
Labels: ready to merge

#6627 chore: Rename `master` to `main` #blacklivesmatter
  .github/PULL_REQUEST_TEMPLATE.md
  docs/CONTRIBUTING-es.md
  docs/CONTRIBUTING.md
Labels: ready to merge

#6629 Missing C++ book added
  books/free-programming-books-fi.md
Labels: waiting for changes
