Repository EbookFoundation/free-programming-books, pull requests merged in 2021-10, with the labels that each got.

#5590 Add Hebrew online courses
  README.md
  courses/free-courses-he.md
Labels: New Feature

#5592 Add Hebrew online books
  README.md
  books/free-programming-books-he.md
Labels: New Feature

#5593 Add some learning reference in ID
  courses/free-courses-id.md
Labels: conflicts

#5595 fix a java course link by programmerzamannow
  courses/free-courses-id.md
Labels: conflicts

#5669 HOWTO in Russian
  HOWTO-es.md
  HOWTO-fa_IR.md
  HOWTO-fr.md
  HOWTO-hi.md
  HOWTO-pt_BR.md
  HOWTO-ru.md
  HOWTO-zh.md
  HOWTO-zh_TW.md
  HOWTO.md
Labels: New Feature

#5678 fix(docs): Update HOWTO-hi.md with current CI system
  HOWTO-hi.md
Labels: please resubmit PR

#5708 chore: add svelte resource to free-courses-id
  courses/free-courses-id.md
Labels: please resubmit PR

#5714 Added Git & GitHub tutorial playlist at free-courses-en.md
  courses/free-courses-en.md
Labels: please resubmit PR

#5742 Added Deep Learning with PyTorch course in free-courses-en.md
  courses/free-courses-en.md
Labels: please resubmit PR

#5719 AWS S3 Cost optimisation ebook
  books/free-programming-books-subjects.md
Labels: conflicts

#5720 Add german contributing guidelines
  CONTRIBUTING-de.md
  CONTRIBUTING-es.md
  CONTRIBUTING-fa_IR.md
  CONTRIBUTING-fr.md
  CONTRIBUTING-ru.md
  CONTRIBUTING-vn.md
  CONTRIBUTING-zh.md
  CONTRIBUTING-zh_TW.md
  CONTRIBUTING.md
Labels: New Feature, please resubmit PR

#5679 Add Mastering Roda to Ruby's section
  books/free-programming-books-langs.md
Labels: please resubmit PR

#5726 ➕ add ML books and courses
  books/free-programming-books-langs.md
  books/free-programming-books-subjects.md
  courses/free-courses-en.md
Labels: please resubmit PR

#5755 Update free-courses-it.md
  courses/free-courses-it.md
Labels: please resubmit PR

#5764 Adding phpdocumentor
  books/free-programming-books-langs.md
Labels: please resubmit PR

#5765 Add C Programming Tutorial book
  books/free-programming-books-langs.md
Labels: not_free?

#5771 Update free-courses-es.md
  courses/free-courses-es.md
Labels: question, please resubmit PR

#5772 Add SQL course
  courses/free-courses-es.md
Labels: please resubmit PR

#5774 Added English, By subject to next line
  README.md
Labels: question

#5779 Add web design book
  books/free-programming-books-subjects.md
Labels: please resubmit PR

#5784 Add course on full stack development
  courses/free-courses-en.md
Labels: please resubmit PR

#5785 Removed dead links
  books/free-programming-books-langs.md
Labels: question

#5786 Added in interactive programming resources for Go, Kotlin, and added in an R section
  more/free-programming-interactive-tutorials-en.md
Labels: please resubmit PR

#5787 books: add `Conquer the Command Line`
  books/free-programming-books-langs.md
Labels: please resubmit PR

#5819 Add German HOWTO & CODEOFCONDUCT file
  CODE_OF_CONDUCT-de.md
  HOWTO-de.md
  HOWTO-es.md
  HOWTO-fa_IR.md
  HOWTO-fr.md
  HOWTO-hi.md
  HOWTO-pt_BR.md
  HOWTO-ru.md
  HOWTO-zh.md
  HOWTO-zh_TW.md
  HOWTO.md
Labels: New Feature

#5849 chore: patch R heading level of #5786
  more/free-programming-interactive-tutorials-en.md
Labels: ready to merge

#5672 Add 4 course in free-courses-id.md
  courses/free-courses-id.md
Labels: please resubmit PR

#5781 Add book Bash Scripting
  books/free-programming-books-pt_BR.md
Labels: please resubmit PR, linter error

#5799 HTML5 Canvas in Indonesian Language
  courses/free-courses-id.md
Labels: please resubmit PR

#5815 Added New Courses and fixed a typo
  courses/free-courses-hi.md
Labels: conflicts

#5855 update free-Courses-en
  courses/free-courses-en.md
Labels: ready to merge

#5732 Translated files in Italian
  CODE_OF_CONDUCT-it.md
  CONTRIBUTING-it.md
  HOWTO-it.md
Labels: New Feature, ready to merge

#5865 Adds "Programming, Data Structures And Algorithms Using Python" course
  courses/free-courses-en.md
Labels: ready to merge

#5615 fix(docs): wrong COC contact and links (es, hi)
  CODE_OF_CONDUCT-es.md
  CODE_OF_CONDUCT-hi.md
Labels: ready to merge

#5773 Add Basic Machine Learning Blog Course
  courses/free-courses-vi.md
Labels: question, please resubmit PR

#5900 Adding URL to CONTRIBUTING.md Indonesia version
  CONTRIBUTING.md
Labels: ready to merge

#5910 fix: incorrect fullwidth in CONTRIBUTING-zh_TW.md
  CONTRIBUTING-zh_TW.md
Labels: ready to merge

#5898 Fixing format CONTRIBUTING-id.md
  CONTRIBUTING-id.md
Labels: question, discussion

#5906 Add Swedish language to HOWTO!
  HOWTO-se.md
Labels: question, New Feature

#5908 Add Korean language to HOWTO!
  CODE_OF_CONDUCT-kr.md
  HOWTO-bs.md
  HOWTO-de.md
  HOWTO-es.md
  HOWTO-fa_IR.md
  HOWTO-fr.md
  HOWTO-hi.md
  HOWTO-kr.md
  HOWTO-pt_BR.md
  HOWTO-ru.md
  HOWTO-zh.md
  HOWTO-zh_TW.md
Labels: duplicate, New Feature, conflicts

#5882 add Java Foundation Course
  courses/free-courses-hi.md
Labels: ready to merge

#5789 Adding Module Patterns book
  books/free-programming-books-langs.md
Labels: ready to merge

#5905 Improvements to the german howto and contribution files
  CONTRIBUTING-de.md
  HOWTO-de.md
Labels: ready to merge

#5925 added programming in Java by NPTEL
  courses/free-courses-en.md
Labels: ready to merge

#5937 added a react book from digitalocean
  books/free-programming-books-langs.md
Labels: ready to merge

#5945 Added respective authors to the links
  more/free-programming-cheatsheets.md
Labels: ready to merge

#5868 Added new course and fixed some info
  books/free-programming-books-ko.md
Labels: question

#5871 add electron book from syncfusion
  books/free-programming-books-langs.md
Labels: question

#5888 Added two english Data structures and algorithms courses in free-programming-books/courses/free-courses-en.md file, Resolve #5872
  courses/free-courses-en.md
Labels: question

#5890 Restructured the Books to add new Subsection : MongoDB and added The …
  books/free-programming-books-langs.md
Labels: not_free?, please resubmit PR

#5936 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: question

#5909 Add svelte resources
  books/free-programming-books-langs.md
  courses/free-courses-en.md
Labels: ready to merge

#5893 added Go lang to courses-th.md
  books/free-programming-books-th.md
Labels: ready to merge

#6506 -Added Go Bootcamp and Python App deploy
  courses/free-courses-en.md
  courses/free-courses-pt_BR.md
Labels: waiting for changes

#6509 Add Computer Theory Book in Spanish Books
  books/free-programming-books-es.md
Labels: ready to merge

#6530 Update CONTRIBUTING-ko.md
  CONTRIBUTING-ko.md
Labels: ready to merge

#6532 Translate HOWTO.md to Greek
  HOWTO-el.md
Labels: ready to merge

#6505 Added Some Udacity Courses
  courses/free-courses-en.md
Labels: waiting for changes

#6496 Update free-programming-books-langs.md
  books/free-programming-books-langs.md
Labels: ready to merge

#6497 adding new Arabic books and adding Author for a book
  books/free-programming-books-ar.md
Labels: ready to merge

#6519 Changed the URL for C for Python Programmers by Carl Burch
  books/free-programming-books-langs.md
Labels: ready to merge

#6536 New C Book
  books/free-programming-books-pt_BR.md
Labels: ready to merge

#6081 added Django python web devlopment courses
  courses/free-courses-en.md
Labels: waiting for changes

#6217 Design Patterns added
  books/free-programming-books-fa_IR.md
Labels: question, waiting for changes

#6485 Update programming playgrounds list with Scratch
  more/free-programming-playgrounds.md
Labels: question, waiting for changes

#6502 Add Course Playlists to free-courses-hi.md
  courses/free-courses-hi.md
Labels: waiting for changes

#6544 Remove techotopia, linuxtopia resources
  books/free-programming-books-langs.md
Labels: ready to merge

#6548 Add course to courses\free-courses-tr.md
  courses/free-courses-tr.md
Labels: ready to merge

#6549 Programiz, another shell for python
  more/free-programming-playgrounds.md
Labels: ready to merge

#6552 Fix title in document
  casts/free-podcasts-screencasts-fr.md
Labels: ready to merge

#6551 added free courses
  courses/free-courses-en.md
Labels: waiting for changes

#6546 Added The Little Ecto Cookbook
  books/free-programming-books-langs.md
Labels: waiting for changes

#6265 Update free-courses-pl.md
  courses/free-courses-pl.md
Labels: waiting for changes
