Repository EbookFoundation/free-programming-books, pull requests merged in 2021-12, with the labels that each got.

#6631 Add badges
  README.md
  docs/CONTRIBUTING.md
Labels: discussion

#6646 Remove `The Vim Blog` podcast
  casts/free-podcasts-screencasts-en.md
Labels: ready to merge

#6626 chore(books-bn): split bangla books - courses
  README.md
  books/free-programming-books-bn.md
  courses/free-courses-bn.md
Labels: ready to merge

#6645 added free courses bahasa Indonesia
  courses/free-courses-id.md
Labels: waiting for changes
