Repository EbookFoundation/free-programming-books, pull requests merged in 2022-08, with the labels that each got.

#6981 Added podcasts in Arabic
  casts/free-podcasts-screencasts-ar.md
Labels: 👀 Needs Review, 🗣 locale:ar

#6977 feat(books): add `Code Simplicity: The Fundamentals of Software` by Max Kanat-Alexander
  books/free-programming-books-subjects.md
Labels: 🚀 ready to merge, 🗣 locale:en

#6978 docs: update statistic counters of the repo
  README.md
Labels: 🚀 ready to merge, 🗣 locale:en

#6979 Add books in Latvian
  README.md
  books/free-programming-books-lv.md
Labels: 🚀 ready to merge, 🗣 locale:lv

#6959 Add several `Scaler Topics` tutorials
  more/free-programming-interactive-tutorials-en.md
Labels: 🗣 locale:en

#6984 build: changed name of 'main.yml' workflow to 'check-urls.yml'
  .github/workflows/check-urls.yml
Labels: 🚀 ready to merge, 🤖 automation

#6987 Move an AWS course from books to courses section
  books/free-programming-books-ar.md
  courses/free-courses-ar.md
Labels: 🚀 ready to merge, 🗣 locale:ar

#6989 Add Hesham Asem's courses about Machine and Deep learning and NLP
  courses/free-courses-ar.md
Labels: 🚀 ready to merge, 🗣 locale:ar

#6986 fix(books): free-programming-books-zh broken links
  books/free-programming-books-zh.md
Labels: 👀 Needs Review, 🗣 locale:zh

#6820 security(workflow): Set permissions for GitHub actions
  .github/workflows/fpb-lint.yml
Labels: 🚀 ready to merge, 🤖 automation

#6988 fix: homogenize markdown across files using markdownlint rules
  books/free-programming-books-ar.md
  books/free-programming-books-cs.md
  books/free-programming-books-de.md
  books/free-programming-books-el.md
  books/free-programming-books-es.md
  books/free-programming-books-et.md
  books/free-programming-books-fa_IR.md
  books/free-programming-books-fr.md
  books/free-programming-books-he.md
  books/free-programming-books-hu.md
  books/free-programming-books-id.md
  books/free-programming-books-it.md
  books/free-programming-books-ja.md
  books/free-programming-books-ko.md
  books/free-programming-books-langs.md
  books/free-programming-books-nl.md
  books/free-programming-books-pl.md
  books/free-programming-books-pt_BR.md
  books/free-programming-books-ro.md
  books/free-programming-books-ru.md
  books/free-programming-books-sk.md
  books/free-programming-books-subjects.md
  books/free-programming-books-th.md
  books/free-programming-books-tr.md
  books/free-programming-books-uk.md
  books/free-programming-books-zh.md
  casts/free-podcasts-screencasts-en.md
  casts/free-podcasts-screencasts-pt_BR.md
  casts/free-podcasts-screencasts-ru.md
  courses/free-courses-ar.md
  courses/free-courses-bn.md
  courses/free-courses-de.md
  courses/free-courses-en.md
  courses/free-courses-es.md
  courses/free-courses-fa_IR.md
  courses/free-courses-fr.md
  courses/free-courses-hi.md
  courses/free-courses-id.md
  courses/free-courses-it.md
  courses/free-courses-kk.md
  courses/free-courses-km.md
  courses/free-courses-ko.md
  courses/free-courses-ml.md
  courses/free-courses-pt_BR.md
  courses/free-courses-ru.md
  courses/free-courses-si.md
  courses/free-courses-th.md
  courses/free-courses-vi.md
  more/free-programming-cheatsheets.md
  more/free-programming-interactive-tutorials-en.md
  more/free-programming-interactive-tutorials-ja.md
  more/free-programming-interactive-tutorials-ru.md
  more/free-programming-playgrounds.md
Labels: 🗣 locale:en, 🗣 locale:es, 🗣 locale:fr, 🗣 locale:de, 🗣 locale:it, 🗣 locale:pt, 🗣 locale:ru, 🗣 locale:zh, 🗣 locale:el, 🗣 locale:id, 🗣 locale:th, 🗣 locale:pl, 🗣 locale:hi, 🗣 locale:ar, 🗣 locale:ko, 🗣 locale:vi, 🗣 locale:tr, 🗣 locale:bn, 🗣 locale:ml, 🗣 locale:fa_IR, 🗣 locale:nl, 🗣 locale:km, 🗣 locale:uk, 🗣 locale:cs, 🗣 locale:et, 🗣 locale:he, 🗣 locale:hu, 🗣 locale:ro, 🗣 locale:sk, 🗣 locale:kk, 🗣 locale:si

#6882 Add Tailwindcsss ,Vue and Svelte structured properly with `Learn with Sumit` resources
  courses/free-courses-bn.md
Labels: 🚀 ready to merge, stale, 🗣 locale:bn

#6994 Add several Malayalam courses authored by `Yes Tech Media`, `Tintu Vlogger` and `Brototype Malayalam`
  courses/free-courses-ml.md
Labels: 🚀 ready to merge, 🗣 locale:ml

#7000 Register Tamil locale entry (part of #7001)
  README.md
Labels: 🚀 ready to merge, 🗣 locale:ta

#7002 Added some necessary youtube playlist of Bengali Language
  courses/free-courses-bn.md
Labels: 🗣 locale:bn

#7008 Update free-courses-en.md
  courses/free-courses-en.md
Labels: waiting for changes, 🗣 locale:en

#7004 Add `Debug Media`'s playlists to malayalam Git, HTML, CSS, React sections
  courses/free-courses-ml.md
Labels: waiting for changes, 🗣 locale:ml

#7019 fix problem from too-fast merge of #7008
  courses/free-courses-en.md
Labels: 🚀 ready to merge, 🗣 locale:en

#7006 Update `free-courses-hi.md` with Shell, Flutter, Bootstrap, jQuery, Node.js lists
  courses/free-courses-hi.md
Labels: 🚀 ready to merge, 🗣 locale:hi

#7021 fix spaces and dots in fragment id of markdown links
  books/free-programming-books-langs.md
  docs/CONTRIBUTING-vi.md
Labels: question, waiting for changes, 🐛 BUG

#7020 change upper case to lower cas in fragment ids
  books/free-programming-books-az.md
  books/free-programming-books-fr.md
  books/free-programming-books-ko.md
  books/free-programming-books-ta.md
  courses/free-courses-ru.md
  more/free-programming-cheatsheets.md
Labels: 🚀 ready to merge, 🐛 BUG

#7025 Added the Vzhůru dolů podcast
  casts/free-podcasts-screencasts-cs.md
Labels: 🚀 ready to merge, 🗣 locale:cs

#7010 Add Django and Flash playlists to `free-courses-ko.md`
  courses/free-courses-ko.md
Labels: 🚀 ready to merge, 🗣 locale:ko

#7001 Create `free-courses-ta.md` with several courses in Tamil
  courses/free-courses-ta.md
Labels: 🚀 ready to merge, 🗣 locale:ta

#7032 fix: preserve `title - author` format
  books/free-programming-books-es.md
  books/free-programming-books-ja.md
  books/free-programming-books-langs.md
  books/free-programming-books-ro.md
  books/free-programming-books-subjects.md
  courses/free-courses-en.md
  courses/free-courses-si.md
  more/free-programming-interactive-tutorials-en.md
Labels: 🚀 ready to merge, 🗣 locale:en, 🗣 locale:es, 🗣 locale:jp, 🗣 locale:si

#7033 Add "Qt6 QML Book" by Johan Thelin, Jürgen Bocklage-Ryannel, Cyril Lorquet (HTML, PDF)
  books/free-programming-books-langs.md
Labels: waiting for changes, 🗣 locale:en

#7035 Update listing for SICP book
  books/free-programming-books-subjects.md
Labels: 🗣 locale:en

#7026 remove non-free leanpub books
  books/free-programming-books-es.md
  books/free-programming-books-id.md
  books/free-programming-books-langs.md
  books/free-programming-books-pt_BR.md
  books/free-programming-books-ru.md
  books/free-programming-books-subjects.md
  books/free-programming-books-tr.md
Labels: 🚀 ready to merge, 🗣 locale:en, 🗣 locale:es, 🗣 locale:pt, 🗣 locale:ru, 🗣 locale:id, 🗣 locale:tr

#6954 Add PingCAP's `TiDB Introduction` book
  books/free-programming-books-langs.md
Labels: 👥 discussion, 🚀 ready to merge, 🗣 locale:en

#7038 fix: fully patch the `MD007/ul-indent` rule forgotten at #6988
  books/free-programming-books-cs.md
Labels: 🗣 locale:cs

#7039 chore: it's `Vue.js` a Javascript framework to build SPAs
  books/free-programming-books-et.md
  books/free-programming-books-id.md
  courses/free-courses-bn.md
  courses/free-courses-id.md
  courses/free-courses-it.md
  courses/free-courses-pl.md
  courses/free-courses-pt_BR.md
  courses/free-courses-vi.md
Labels: 🗣 locale:it, 🗣 locale:pt, 🗣 locale:id, 🗣 locale:pl, 🗣 locale:vi, 🗣 locale:bn, 🗣 locale:et

#7043 security: GitHub Workflows security hardening
  .github/workflows/check-urls.yml
Labels: 🚀 ready to merge, urlchecker, 🤖 automation

#7045 Update free-programming-books-id.md
  books/free-programming-books-id.md
Labels: 🚀 ready to merge, 🗣 locale:id

#7040 feat: add 3 GitGuardian's cheatsheets about Git, GitHub & Docker
  more/free-programming-cheatsheets.md
Labels: waiting for changes, 🗣 locale:en

#6962 chore: maintenance of `Curso em Video` resources
  casts/free-podcasts-screencasts-pt_BR.md
  courses/free-courses-pt_BR.md
Labels: 🗣 locale:pt

#7046 ci(check-urls): fix push crash on new branch creation + render awesome_bot report
  .github/actions/awesomebot-gh-summary-action/action.yml
  .github/workflows/check-urls.yml
Labels: urlchecker, 🤖 automation
