Repository EbookFoundation/free-programming-books, pull requests merged in 2022-06, with the labels that each got.

#6873 added a new Go online course
  courses/free-courses-bn.md
Labels: question, 🗣 locale:bn

#6876 Updating link for 'Modelling Creativity: Case studies for python'
  books/free-programming-books-langs.md
Labels: 👥 discussion, 🗣 locale:en

#6871 Add new Blockchain book
  books/free-programming-books-subjects.md
Labels: 🚀 ready to merge, 🗣 locale:en

#6845 add five books and create two sections
  books/free-programming-books-ar.md
Labels: 🚀 ready to merge, 🗣 locale:ar

#6857 Add lua ebook.
  books/free-programming-books-langs.md
Labels: waiting for changes, linter error, 🗣 locale:en

#6884 Update free-programming-books-et.md
  books/free-programming-books-et.md
Labels: waiting for changes, 👀 Needs Review, 🗣 locale:et

#6877 added a few Dart and Flutter online courses
  courses/free-courses-en.md
Labels: 🚀 ready to merge, 🗣 locale:en

#6878 docs(CONTRIBUTING): improve guidelines
  docs/CONTRIBUTING.md
Labels: help wanted, 🗣 translations, 🗣 locale:en

#6859 Add grain docs
  books/free-programming-books-langs.md
Labels: 🚀 ready to merge, 🗣 locale:en

#6886 adding the book Data Centric Intro to Computation
  books/free-programming-books-subjects.md
Labels: 🚀 ready to merge, 🗣 locale:en

#6889 add link to search when we ask submitters to search
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 🚀 ready to merge

#6888 make search more prominent
  README.md
Labels: 🚀 ready to merge

#6891 Update free-courses-bn.md
  courses/free-courses-bn.md
Labels: waiting for changes, 🗣 locale:bn
