Repository EbookFoundation/free-programming-books, pull requests merged in 2022-03, with the labels that each got.

#6743 Adding sass book(pdf)
  books/free-programming-books-langs.md
Labels: waiting for changes

#6744 Add "The Ultimate Guide to React Native Optimization" book
  books/free-programming-books-langs.md
Labels: 🗣 locale:en

#6739 chore: keeping spelling consistencies same. `GitHub` and `YouTube` trademarks
  books/free-programming-books-es.md
  books/free-programming-books-langs.md
  courses/free-courses-en.md
  courses/free-courses-es.md
  courses/free-courses-id.md
  courses/free-courses-pt_BR.md
  docs/HOWTO-ko.md
Labels: 🚀 ready to merge, 🗣 locale:en, 🗣 locale:es, 🗣 locale:pt, 🗣 locale:id, 🗣 locale:ko

#5521 ci(deps): configure dependabot for github-actions
  .github/dependabot.yml
Labels: New Feature, 👥 discussion, help wanted, 👀 Needs Review, 🤖 automation

#6751 Added "Solidity" to the table of contents.
  books/free-programming-books-langs.md
Labels: waiting for changes, 🗣 locale:en

#6749 Add Arduino books in pt-BR
  books/free-programming-books-pt_BR.md
Labels: 🚀 ready to merge, 🗣 locale:pt

#6766 add new arabic course
  courses/free-courses-ar.md
Labels: 🚀 ready to merge, 🗣 locale:ar

#6771 fix: Update Java mattone (a different version).
  books/free-programming-books-it.md
Labels: 🚀 ready to merge, 🗣 locale:it, urlchecker

#6762 add some courses
  courses/free-courses-id.md
Labels: 🚀 ready to merge, 🗣 locale:id

#6768 Add linux book
  books/free-programming-books-pt_BR.md
Labels: 👀 Needs Review

#6769 fix: use new Google CodeJam practice archive website
  more/problem-sets-competitive-programming.md
Labels: 🚀 ready to merge, 🗣 locale:en, urlchecker

#6774 add the next.js handbook translated by abdelhadi
  books/free-programming-books-ar.md
Labels: 🚀 ready to merge, 🗣 locale:ar

#6776 Added MIT CS and DS courses
  courses/free-courses-en.md
Labels: waiting for changes, 🚀 ready to merge, 🗣 locale:en

#6761 Add aprende python
  books/free-programming-books-es.md
Labels: 🚀 ready to merge, 🗣 locale:es

#6697 feat(docs): Add repo stats badges
  README.md
Labels: 👥 discussion, help wanted, 👀 Needs Review

#6770 fix: archive past KDD cups and update main resource link to current year
  more/problem-sets-competitive-programming.md
Labels: 🚀 ready to merge, 🗣 locale:en, urlchecker

#6772 Add AdventJS. A spanish javascript problemset website by midudev
  more/problem-sets-competitive-programming.md
Labels: question, 🗣 locale:es

#6767 Add Quantum Computing
  books/free-programming-books-subjects.md
Labels: 🚀 ready to merge, 🗣 locale:en

#6696 config: update `.editorconfig` parameters according to current format of files
  .editorconfig
Labels: 👀 Needs Review

#6778 Update free-courses-en.md
  courses/free-courses-en.md
Labels: 🚀 ready to merge, 🗣 locale:en

#6785 Normalize CodeWithHarry credits
  courses/free-courses-en.md
  courses/free-courses-hi.md
Labels: 🗣 locale:en, 🗣 locale:hi

#6781 Update entries for Beej's Guides
  README.md
  books/free-programming-books-de.md
  books/free-programming-books-dk.md
  books/free-programming-books-fr.md
  books/free-programming-books-hu.md
  books/free-programming-books-it.md
  books/free-programming-books-langs.md
  books/free-programming-books-pl.md
  books/free-programming-books-pt_BR.md
  books/free-programming-books-ro.md
  books/free-programming-books-ru.md
  books/free-programming-books-sr.md
  books/free-programming-books-subjects.md
  books/free-programming-books-tr.md
  books/free-programming-books-zh.md
Labels: 🚀 ready to merge, 🗣 locale:en, 🗣 locale:fr, 🗣 locale:de, 🗣 locale:it, 🗣 locale:ru, 🗣 locale:zh, 🗣 locale:pl, 🗣 locale:tr, 🗣 locale:dk, 🗣 locale:hu, 🗣 locale:ro, 🗣 locale:sr

#6786 Add JSP (Java server pages) and servlet basics
  courses/free-courses-en.md
Labels: 🚀 ready to merge, 🗣 locale:en

#6787 chore: Normalize `Learn With Sumit` attribution
  courses/free-courses-bn.md
Labels: 🚀 ready to merge, 🗣 locale:bn

#6788 chore: Normalize `Silicium` attribution playlists
  courses/free-courses-fa_IR.md
Labels: 🚀 ready to merge, 🗣 locale:tr, 🗣 locale:fa_IR

#6789 fix: ensure crosslinks format
  courses/free-courses-en.md
Labels: 🚀 ready to merge, 🐛 BUG, 🗣 locale:en

#6790 chore: standardize `Programming with Mosh` instructor
  courses/free-courses-en.md
  more/free-programming-cheatsheets.md
Labels: 👥 discussion, 🗣 locale:en

#6800 Add 'Learn you some Erlang for great good!' translation
  books/free-programming-books-ja.md
  books/free-programming-books-langs.md
Labels: 🚀 ready to merge, 🗣 locale:en, 🗣 locale:jp

#6802 Add "Desenvolvimento de Aplicações Web em Java e Outras Tecnologias" to `pt_BR` books
  books/free-programming-books-pt_BR.md
Labels: 🚀 ready to merge, 🗣 locale:pt

#6752 Add an AWS free complete course in Arabic
  books/free-programming-books-ar.md
Labels: 🚀 ready to merge, stale, 🗣 locale:ar

#6808 chore: Improve `eXcript` resources metadata
  courses/free-courses-pt_BR.md
Labels: 🗣 locale:pt

#6809 chore: homogenize `Curso em Vídeo` - `Gustavo Guanabara` resources
  casts/free-podcasts-screencasts-pt_BR.md
  courses/free-courses-pt_BR.md
Labels: 🗣 locale:pt

#6810 chore: Improve metadata about `Flutter in Action` by Eric Windmill
  books/free-programming-books-langs.md
Labels: 🗣 locale:en
