Repository EbookFoundation/free-programming-books, pull requests merged in 2022-05, with the labels that each got.

#6835 Update free-courses-ar.md
  courses/free-courses-ar.md
Labels: 🚀 ready to merge, 🗣 locale:ar

#6837 add new araic courses
  courses/free-courses-ar.md
Labels: 🚀 ready to merge, 🗣 locale:ar

#6838 Add Japanese course and interactive tutorials
  README.md
  courses/free-courses-ja.md
  more/free-programming-interactive-tutorials-ja.md
Labels: New Feature, 🚀 ready to merge, 🗣 locale:jp

#6844 Add more GTK books
  books/free-programming-books-subjects.md
Labels: 🚀 ready to merge, 🗣 locale:en

#6843 Added Useful Links
  books/free-programming-books-langs.md
Labels: waiting for changes
