Repository EbookFoundation/free-programming-books, pull requests merged in 2022-11, with the labels that each got.

#9153 Add Linear Algebra Textbook
  more/free-programming-interactive-tutorials-en.md
Labels: :rocket: ready to merge

#9164 Add Computer Vision book from standford
  books/free-programming-books-subjects.md
Labels: :rocket: ready to merge

#9172 Ft new resource
  courses/free-courses-en.md
Labels: :rocket: ready to merge

#9002 Added python book in Ukrainian
  books/free-programming-books-uk.md
Labels: :speaking_head: locale:uk

#9165 Complete entry for Computer Science One textbook
  books/free-programming-books-subjects.md
Labels: :rocket: ready to merge

#9166 Complete entry for Computer Science Two textbook
  books/free-programming-books-subjects.md
Labels: :rocket: ready to merge

#9167 add new Book - Knowledge Graphs
  books/free-programming-books-langs.md
Labels: :rocket: ready to merge

#8189 Adding sigmageek in competitive programming
  more/problem-sets-competitive-programming.md
Labels: question

#8197 docs(CONTRIBUTING): translate #8152 to spanish
  docs/CONTRIBUTING-es.md
Labels: :speaking_head: translations, :speaking_head: locale:es

#8225 Update free-programming-books-subjects.md
  books/free-programming-books-subjects.md
Labels: waiting for changes

#8261 Add "Shell scripting with Node.js"
  books/free-programming-books-langs.md
Labels: waiting for changes

#8565 added C# Sinhala course tutorial series
  courses/free-courses-si.md
Labels: waiting for changes

#8613 Add Node.js and PHP learning resource in Indonesian
  books/free-programming-books-id.md
Labels: changes made

#8621 Updated courses in Telugu language
  courses/free-courses-te.md
Labels: waiting for changes

#8628 Create Norwegian code of conduct
  docs/CODE_OF_CONDUCT-no.md
  docs/README.md
Labels: :speaking_head: translations

#8636 Added cheatsheet for Cron
  more/free-programming-cheatsheets.md
Labels: question

#8801 বাংলা বানান সংশোধন
  docs/HOWTO-bn.md
Labels: help wanted, :speaking_head: locale:bn

#8803 Add some free courses in Nepali and Translate Contributing in Nepali
  courses/free-courses-ne.md
  docs/CONTRIBUTING-np.md
  docs/README.md
Labels: waiting for changes, help wanted, :speaking_head: translations, :speaking_head: locale:ne

#8651 Added a new book "DBMS"
  books/free-programming-books-langs.md
Labels: changes made

#8865 Update link for-advanced Scala with Cats book
  books/free-programming-books-langs.md
Labels: waiting for changes

#8878 Add book to free-programming-books-subjects
  books/free-programming-books-subjects.md
Labels: waiting for changes

#8897 Added Redux Tutorial
  books/free-programming-books-id.md
  books/free-programming-books-langs.md
Labels: waiting for changes

#8731 Added typescript playground
  more/free-programming-playgrounds.md
Labels: changes made

#8734 Added "Introdução à Linguagem de Programação Go" and "Go 101" course
  courses/free-courses-pt_BR.md
Labels: changes made

#8759 최신 개정판으로 링크 업데이트
  books/free-programming-books-ko.md
Labels: changes made

#8936 Update free-programming-books-ar.md
  books/free-programming-books-ar.md
Labels: waiting for changes

#9018 add Kotlin for Android book in Spanish
  books/free-programming-books-es.md
Labels: waiting for changes

#9079 Add numpy and pandas cheatsheet #9049
  more/free-programming-cheatsheets.md
Labels: waiting for changes

#8857 Updated Hindi books resources
  books/free-programming-books-hi.md
Labels: changes made

#8932 Add course Kotlin Basics free ptBR
  courses/free-courses-pt_BR.md
Labels: changes made

#8933 add free course on ionic 6 ptBR
  courses/free-courses-pt_BR.md
Labels: :speaking_head: locale:pt, changes made

#8992 Added Course Instructor Name of Stanford's Compiler Course
  courses/free-courses-en.md
Labels: changes made

#8997 Front-end Development Course is added in free-courses-hi.md
  courses/free-courses-hi.md
Labels: changes made

#9020 Update free-courses-th.md
  courses/free-courses-th.md
Labels: changes made

#9013 Update free-courses-tr.md
  courses/free-courses-tr.md
Labels: waiting for changes

#8559 Update free-courses-hi.md
  courses/free-courses-hi.md
Labels: changes made

#7186 Added Web3 Content
  courses/free-courses-en.md
Labels: :speaking_head: locale:en, changes made

#7205 docs: add python courses and books in indonesia language
  books/free-programming-books-id.md
  courses/free-courses-id.md
Labels: waiting for changes, :speaking_head: locale:id

#9176 Update free-courses-tr.md
  courses/free-courses-tr.md
Labels: waiting for changes

#9110 Update free-programming-books-fr.md
  books/free-programming-books-fr.md
Labels: waiting for changes

#9154 Gautham/iOS resource (Requested changes done)
  courses/free-courses-en.md
Labels: :rocket: ready to merge

#7374 Added Kubernetes and Redux Courses for English
  courses/free-courses-en.md
Labels: :speaking_head: locale:en, changes made

#8561 Added a Book About C# Language
  books/free-programming-books-pt_BR.md
Labels: changes made

#8885 Added IBM course
  courses/free-courses-en.md
Labels: changes made

#8930 GitHub and version control free course ptBR
  courses/free-courses-pt_BR.md
Labels: changes made

#8934 Add free course on React Native ptBR
  courses/free-courses-pt_BR.md
Labels: :speaking_head: locale:pt, changes made

#8887 Added Terraform courses
  courses/free-courses-en.md
Labels: changes made

#8113 Added Haskell course titled Zor Yoldan Haskell
  books/free-programming-books-tr.md
Labels: linter error, changes made

#8253 Add Flask Cheat Sheet
  more/free-programming-cheatsheets.md
Labels: changes made

#8778 Added Introduction to DataFrames course by Bogumił Kamiński
  courses/free-courses-en.md
Labels: changes made

#8853 added a new data structure course in python
  courses/free-courses-en.md
Labels: changes made

#7556 Added 2d interactive game development course
  courses/free-courses-en.md
Labels: :speaking_head: locale:en, changes made

#8766 Added a helpful resource
  books/free-programming-books-langs.md
Labels: linter error, changes made

#9180 Replaced dead link
  books/free-programming-books-it.md
Labels: waiting for changes

#8010 Feature add course
  more/free-programming-playgrounds.md
Labels: waiting for changes

#9181 add Hands-on Python 3 Tutorial
  books/free-programming-books-langs.md
Labels: :rocket: ready to merge

#7713 Add a Java Thai book
  books/free-programming-books-th.md
Labels: waiting for changes

#7687 Add Go/Rust/Ruby courses from learnxinyminutes
  books/free-programming-books-langs.md
Labels: question

#7690 Added Clojure and Lua Tutorials
  courses/free-courses-en.md
Labels: changes made

#7882 contributing to interactive-tutorials
  more/free-programming-interactive-tutorials-en.md
Labels: changes made

#7766 Add Statistics for Applications
  courses/free-courses-en.md
Labels: changes made

#7773 Add next js tutorial
  books/free-programming-books-id.md
Labels: changes made

#7810 Update free-programming-books-ko.md
  books/free-programming-books-ko.md
Labels: question

#9184 Update free-courses-bn.md
  courses/free-courses-bn.md
Labels: waiting for changes

#7856 Added hindi book in C programming
  books/free-programming-books-hi.md
Labels: changes made

#8053 Add newer edition of Learn Azure in a Month of Lunches
  books/free-programming-books-subjects.md
Labels: changes made

#8071 Add jQuery, Next.js & Bootstrap resources for courses in couses-hi.md
  courses/free-courses-hi.md
Labels: changes made

#7789 Update problem-sets-competitive-programming.md
  more/problem-sets-competitive-programming.md
Labels: changes made

#7897 Javascript course
  courses/free-courses-en.md
Labels: changes made

#7792 Added more courses for Data Science
  courses/free-courses-en.md
Labels: changes made

#9189 Update free-courses-tr.md
  courses/free-courses-tr.md
Labels: :rocket: ready to merge

#7833 Added two Cheat-sheets
  more/free-programming-cheatsheets.md
Labels: linter error

#7892 Add Data Structure book in Hindi
  books/free-programming-books-hi.md
Labels: waiting for changes

#9185 Java Basic Syntax Bangla Tutorial contributed
  courses/free-courses-bn.md
Labels: :rocket: ready to merge

#7818 Telugu courses added
  README.md
  books/free-programming-books-te.md
  courses/free-courses-te.md
Labels: :speaking_head: locale:te, changes made

#7926 Addes some free sinhala language resources
  courses/free-courses-si.md
Labels: changes made

#7985 Add courses for Docker and Go
  courses/free-courses-en.md
Labels: changes made

#8052 Learning Laravel eBook Added
  books/free-programming-books-langs.md
Labels: changes made

#8079 Add GraphQL cheatsheet
  more/free-programming-cheatsheets.md
Labels: waiting for changes

#8265 Update free-courses-hi.md
  courses/free-courses-hi.md
Labels: waiting for changes

#8332 Update free-courses-en.md
  courses/free-courses-en.md
Labels: changes made

#8445 Update free-courses-hi.md
  courses/free-courses-hi.md
Labels: changes made

#9196 Add "Learn Python 3"
  books/free-programming-books-langs.md
Labels: waiting for changes

#8622 Update free-courses-hi.md
  courses/free-courses-hi.md
Labels: changes made

#8624 Update free-courses-hi.md
  courses/free-courses-hi.md
Labels: changes made

#8677 New language independent course
  courses/free-courses-pl.md
Labels: changes made

#8883 Added Data Structure courses in Hindi
  courses/free-courses-hi.md
Labels: changes made

#8964 Added java tutorial by javaTpoint
  more/free-programming-interactive-tutorials-en.md
Labels: changes made

#9149 add ebook and course on th resource
  courses/free-courses-th.md
Labels: changes made

#8548 Update free-courses-en.md
  courses/free-courses-en.md
Labels: waiting for changes

#8589 Update free-programming-books-da.md
  books/free-programming-books-da.md
Labels: changes made

#8564 Update free-courses-hi.md
  courses/free-courses-hi.md
Labels: changes made

#8558 added some free next js courses
  courses/free-courses-en.md
Labels: changes made

#8567 add catalan data structures book
  README.md
  books/free-programming-books-ca.md
Labels: :speaking_head: translations, changes made

#8625 Create Norwegian free courses page, added in Java course
  README.md
  courses/free-courses-no.md
Labels: changes made

#8631 Update free-courses-hi.md
  courses/free-courses-hi.md
Labels: changes made

#8643 Adding Java YT Playlist for Beginners
  courses/free-courses-en.md
Labels: changes made

#8675 Jenkins course added under Devops #8215
  courses/free-courses-en.md
Labels: changes made

#8742 Add React Testing Library Course
  courses/free-courses-en.md
Labels: changes made

#8824 added a new course for cpp
  courses/free-courses-hi.md
Labels: changes made

#8844 added redhat courses
  courses/free-courses-en.md
Labels: changes made

#8689 Moved python cheatsheet under cheatsheet file
  more/free-programming-cheatsheets.md
Labels: changes made

#8886 Added Angular Js course
  courses/free-courses-en.md
Labels: changes made

#8867 Adding Java YT course for beginners
  courses/free-courses-en.md
Labels: changes made

#8716 Update free-programming-books-tr.md
  books/free-programming-books-tr.md
Labels: changes made

#8970 feat: :sparkles: new course shell script
  courses/free-courses-pt_BR.md
Labels: :speaking_head: locale:pt

#8966 Added 3 Nodejs books english version
  books/free-programming-books-langs.md
Labels: changes made

#9019 Updated free-courses-en.md
  courses/free-courses-en.md
Labels: changes made

#9025 add javascript course to Romanian books
  books/free-programming-books-ro.md
Labels: changes made

#9045 added "Výkladový slovník Kybernetické bezpečnosti"
  books/free-programming-books-cs.md
Labels: changes made

#9057 Update free-programming-interactive-tutorials-en.md
  more/free-programming-interactive-tutorials-en.md
Labels: changes made

#9125 Added PL/SQL section, added info to SQL books, included Oracle8i doc
  books/free-programming-books-langs.md
Labels: changes made

#9075 Update free-programming-books-th.md
  books/free-programming-books-th.md
Labels: waiting for changes, linter error

#9116 updated free-programming-books-en.md
  books/free-programming-books-langs.md
Labels: changes made

#9134 [free-podcasts-screencasts-fr.md] add new podcast
  casts/free-podcasts-screencasts-fr.md
Labels: changes made

#9159 Add a Django Course
  courses/free-courses-en.md
Labels: changes made

#9161 Added More Courses in Malayalam
  courses/free-courses-ml.md
Labels: changes made

#8632 Create Norwegian How to
  docs/HOWTO-no.md
  docs/README.md
Labels: waiting for changes, :speaking_head: translations

#8835 Added new CTF and problem set sites
  more/problem-sets-competitive-programming.md
Labels: changes made

#8839 added free-courses-yb.md
  courses/free-courses-en.md
Labels: changes made

#8400 Create Code_of_conduct-ben.md
  docs/CODE_OF_CONDUCT-bn.md
  docs/README.md
Labels: :speaking_head: translations

#9198 Added Course for Bash & Shell in Hindi.
  courses/free-courses-hi.md
Labels: waiting for changes
