Repository EbookFoundation/free-programming-books, pull requests merged in 2022-04, with the labels that each got.

#6811 chore: Standardize Flavio Copes' resources
  books/free-programming-books-langs.md
Labels: 🗣 locale:en

#6799 chore: Standardize TutorialsPoint resources
  books/free-programming-books-langs.md
  books/free-programming-books-subjects.md
  courses/free-courses-en.md
Labels: 🚀 ready to merge, 🗣 locale:en

#6813 Add 'An overview of the Odin programming language and its features.'
  books/free-programming-books-langs.md
Labels: waiting for changes, 🗣 locale:en

#6816 Updated the Resources Alphabetically
  more/free-programming-playgrounds.md
Labels: 🚀 ready to merge, 🗣 locale:en

#6818 chore: complete UNAM resources metadata
  books/free-programming-books-es.md
Labels: 🗣 locale:es

#6823 Remove linha de playlist inexistente.
  courses/free-courses-pt_BR.md
Labels: 🚀 ready to merge, 🗣 locale:pt

#6827 Uploaded some italian books and fixed a link
  books/free-programming-books-it.md
Labels: 🚀 ready to merge, 🗣 locale:it

#6828 chore(readme): Apply markdownlint fix for `MD004/ul-style` rule
  README.md
Labels: 🚀 ready to merge, 🐛 BUG, 🗣 locale:en

#6826 Add a search bar to link the original Pages to the searchable Pages
  README.md
Labels: New Feature, 🚀 ready to merge

#6833 Add vlang documentation
  books/free-programming-books-langs.md
Labels: waiting for changes, 🗣 locale:en

#6836 Update free-programming-books-subjects.md
  books/free-programming-books-subjects.md
Labels: 🚀 ready to merge, 🗣 locale:en
