Repository EbookFoundation/free-programming-books, pull requests merged in 2022-02, with the labels that each got.

#6692 Add markdown="1" attribute to div
  README.md
Labels: ready to merge

#6625 docs(contributing): Homogenize format across translated files
  docs/CONTRIBUTING-de.md
  docs/CONTRIBUTING-el.md
  docs/CONTRIBUTING-es.md
  docs/CONTRIBUTING-fa_IR.md
  docs/CONTRIBUTING-fil.md
  docs/CONTRIBUTING-fr.md
  docs/CONTRIBUTING-id.md
  docs/CONTRIBUTING-it.md
  docs/CONTRIBUTING-ko.md
  docs/CONTRIBUTING-pt_BR.md
  docs/CONTRIBUTING-ru.md
  docs/CONTRIBUTING-vi.md
  docs/CONTRIBUTING-zh.md
  docs/CONTRIBUTING-zh_TW.md
  docs/CONTRIBUTING.md
Labels: question

#6695 feat(courses): add golangr.com
  courses/free-courses-en.md
Labels: question, ready to merge

#6589 feat: Add Docker cheatsheets (english & spanish)
  more/free-programming-cheatsheets.md
Labels: Needs Review

#6705 Add book zh 现代 JavaScript 教程
  books/free-programming-books-zh.md
Labels: ready to merge

#6701 fix: RTL support for Arabian docs
  docs/HOWTO-ar.md
Labels: waiting for changes

#6712 Added a resource as a playground - an Educational Visual CPU Simulator
  more/free-programming-playgrounds.md
Labels: ready to merge

#6700 feat: Add `docs/readme.md` + update crosslinks
  README.md
  docs/CODE_OF_CONDUCT-bs.md
  docs/CODE_OF_CONDUCT-de.md
  docs/CODE_OF_CONDUCT-el.md
  docs/CODE_OF_CONDUCT-es.md
  docs/CODE_OF_CONDUCT-fa_IR.md
  docs/CODE_OF_CONDUCT-fil.md
  docs/CODE_OF_CONDUCT-fr.md
  docs/CODE_OF_CONDUCT-hi.md
  docs/CODE_OF_CONDUCT-id.md
  docs/CODE_OF_CONDUCT-it.md
  docs/CODE_OF_CONDUCT-ko.md
  docs/CODE_OF_CONDUCT-pl.md
  docs/CODE_OF_CONDUCT-pt_BR.md
  docs/CODE_OF_CONDUCT-ru.md
  docs/CODE_OF_CONDUCT-uk.md
  docs/CODE_OF_CONDUCT.md
  docs/CONTRIBUTING-de.md
  docs/CONTRIBUTING-el.md
  docs/CONTRIBUTING-es.md
  docs/CONTRIBUTING-fa_IR.md
  docs/CONTRIBUTING-fil.md
  docs/CONTRIBUTING-fr.md
  docs/CONTRIBUTING-id.md
  docs/CONTRIBUTING-it.md
  docs/CONTRIBUTING-ko.md
  docs/CONTRIBUTING-pt_BR.md
  docs/CONTRIBUTING-ru.md
  docs/CONTRIBUTING-vi.md
  docs/CONTRIBUTING-zh.md
  docs/CONTRIBUTING-zh_TW.md
  docs/CONTRIBUTING.md
  docs/HOWTO-ar.md
  docs/HOWTO-bn.md
  docs/HOWTO-bs.md
  docs/HOWTO-de.md
  docs/HOWTO-el.md
  docs/HOWTO-es.md
  docs/HOWTO-fa_IR.md
  docs/HOWTO-fil.md
  docs/HOWTO-fr.md
  docs/HOWTO-hi.md
  docs/HOWTO-id.md
  docs/HOWTO-it.md
  docs/HOWTO-km.md
  docs/HOWTO-ko.md
  docs/HOWTO-nl.md
  docs/HOWTO-pl.md
  docs/HOWTO-pt_BR.md
  docs/HOWTO-ru.md
  docs/HOWTO-sl.md
  docs/HOWTO-sv.md
  docs/HOWTO-th.md
  docs/HOWTO-tr.md
  docs/HOWTO-uk.md
  docs/HOWTO-vi.md
  docs/HOWTO-zh.md
  docs/HOWTO-zh_TW.md
  docs/HOWTO.md
  docs/README.md
Labels: waiting for changes

#6722 fix(docs): Bad target url #6721
  docs/CONTRIBUTING-de.md
  docs/CONTRIBUTING-el.md
  docs/CONTRIBUTING-es.md
  docs/CONTRIBUTING-fa_IR.md
  docs/CONTRIBUTING-fil.md
  docs/CONTRIBUTING-fr.md
  docs/CONTRIBUTING-it.md
  docs/CONTRIBUTING-ko.md
  docs/CONTRIBUTING-pt_BR.md
  docs/CONTRIBUTING-ru.md
  docs/CONTRIBUTING-vi.md
  docs/CONTRIBUTING-zh_TW.md
  docs/CONTRIBUTING.md
Labels: 🚀 ready to merge, 🐛 BUG, 🗣 translation, 🗣 locale:en, 🗣 locale:es, 🗣 locale:fr, 🗣 locale:de, 🗣 locale:it, 🗣 locale:pt, 🗣 locale:ru, 🗣 locale:zh, 🗣 locale:fil, 🗣 locale:el, 🗣 locale:ko, 🗣 locale:vi, 🗣 locale:fa_IR

#6723 fix: Escape pipes. It makes wrong render as tables in Kramdown/GFM engines
  books/free-programming-books-ja.md
  courses/free-courses-ar.md
  courses/free-courses-bn.md
  courses/free-courses-en.md
  courses/free-courses-hi.md
  courses/free-courses-id.md
  courses/free-courses-pt_BR.md
  courses/free-courses-tr.md
  courses/free-courses-vi.md
Labels: 🐛 BUG

#6682 ci(workflows): Update versions
  .github/workflows/fpb-lint.yml
  .github/workflows/main.yml
Labels: question, waiting for changes, 👀 Needs Review

#6725 feat(podcasts): Add mimacom spain podcast
  casts/free-podcasts-screencasts-es.md
Labels: 🚀 ready to merge, 🗣 locale:es

#6726 Fix link to Hebrew assembly book
  books/free-programming-books-he.md
Labels: 🚀 ready to merge, 🐛 BUG, 🗣 locale:he, urlchecker

#6719 docs(contributing): Merge #5816 with #5752 Indonesian translation
  docs/CONTRIBUTING-id.md
Labels: 🚀 ready to merge, 🐛 BUG, 🗣 translations, 🗣 locale:id

#6730 chore: HTML5 anchors compilant `<a name=` > `<a id=`
  books/free-programming-books-ar.md
  books/free-programming-books-bg.md
  books/free-programming-books-cs.md
  books/free-programming-books-de.md
  books/free-programming-books-dk.md
  books/free-programming-books-el.md
  books/free-programming-books-es.md
  books/free-programming-books-et.md
  books/free-programming-books-fi.md
  books/free-programming-books-he.md
  books/free-programming-books-hi.md
  books/free-programming-books-hu.md
  books/free-programming-books-id.md
  books/free-programming-books-it.md
  books/free-programming-books-ja.md
  books/free-programming-books-ko.md
  books/free-programming-books-langs.md
  books/free-programming-books-my.md
  books/free-programming-books-nl.md
  books/free-programming-books-pl.md
  books/free-programming-books-pt_BR.md
  books/free-programming-books-ru.md
  books/free-programming-books-sv.md
  books/free-programming-books-tr.md
  books/free-programming-books-vi.md
  books/free-programming-books-zh.md
  casts/free-podcasts-screencasts-en.md
  courses/free-courses-ar.md
  courses/free-courses-bn.md
  courses/free-courses-de.md
  courses/free-courses-en.md
  courses/free-courses-fi.md
  courses/free-courses-fr.md
  courses/free-courses-he.md
  courses/free-courses-id.md
  courses/free-courses-it.md
  courses/free-courses-ko.md
  courses/free-courses-pl.md
  courses/free-courses-pt_BR.md
  courses/free-courses-ru.md
  courses/free-courses-th.md
  courses/free-courses-uk.md
  courses/free-courses-vi.md
  docs/CONTRIBUTING-de.md
  docs/CONTRIBUTING-el.md
  docs/CONTRIBUTING-es.md
  docs/CONTRIBUTING-fa_IR.md
  docs/CONTRIBUTING-fil.md
  docs/CONTRIBUTING-fr.md
  docs/CONTRIBUTING-it.md
  docs/CONTRIBUTING-ko.md
  docs/CONTRIBUTING-pt_BR.md
  docs/CONTRIBUTING-ru.md
  docs/CONTRIBUTING-vi.md
  docs/CONTRIBUTING-zh.md
  docs/CONTRIBUTING-zh_TW.md
  docs/CONTRIBUTING.md
  more/free-programming-cheatsheets.md
  more/free-programming-interactive-tutorials-en.md
  more/free-programming-playgrounds.md
Labels: 🚀 ready to merge, 🗣 locale:en, 🗣 locale:es, 🗣 locale:fr, 🗣 locale:de, 🗣 locale:it, 🗣 locale:pt, 🗣 locale:ru, 🗣 locale:zh, 🗣 locale:jp, 🗣 locale:fil, 🗣 locale:el, 🗣 locale:id, 🗣 locale:sv, 🗣 locale:th, 🗣 locale:pl, 🗣 locale:hi, 🗣 locale:ar, 🗣 locale:ko, 🗣 locale:vi, 🗣 locale:tr, 🗣 locale:bn, 🗣 locale:ml, 🗣 locale:fa_IR, 🗣 locale:nl, 🗣 locale:km, 🗣 locale:sl, 🗣 locale:uk, 🗣 locale:az, 🗣 locale:bg, 🗣 locale:my, 🗣 locale:cs, 🗣 locale:dk, 🗣 locale:et, 🗣 locale:fi, 🗣 locale:he, 🗣 locale:hu, 🗣 locale:no, 🗣 locale:ro, 🗣 locale:sk, 🗣 locale:ta, 🗣 locale:kk, 🗣 locale:si, 🗣 locale:bs

#6731 chore: gordon.edu is back. unarchive and complete formats
  books/free-programming-books-subjects.md
Labels: question, 🗣 locale:en, urlchecker

#6733 Add `CSS Speedrun` puzzle game by Vincent Will
  more/free-programming-interactive-tutorials-en.md
Labels: 🚀 ready to merge, 🗣 locale:en

#6724 docs(howto): Homogenize HowTo's format across translated files
  docs/HOWTO-ar.md
  docs/HOWTO-bn.md
  docs/HOWTO-bs.md
  docs/HOWTO-de.md
  docs/HOWTO-el.md
  docs/HOWTO-es.md
  docs/HOWTO-fa_IR.md
  docs/HOWTO-fil.md
  docs/HOWTO-fr.md
  docs/HOWTO-hi.md
  docs/HOWTO-id.md
  docs/HOWTO-it.md
  docs/HOWTO-km.md
  docs/HOWTO-ko.md
  docs/HOWTO-nl.md
  docs/HOWTO-pl.md
  docs/HOWTO-pt_BR.md
  docs/HOWTO-ru.md
  docs/HOWTO-sl.md
  docs/HOWTO-sv.md
  docs/HOWTO-th.md
  docs/HOWTO-tr.md
  docs/HOWTO-uk.md
  docs/HOWTO-vi.md
  docs/HOWTO-zh.md
  docs/HOWTO-zh_TW.md
  docs/HOWTO.md
Labels: 🚀 ready to merge, 🗣 translations, 🗣 locale:en, 🗣 locale:es, 🗣 locale:fr, 🗣 locale:de, 🗣 locale:it, 🗣 locale:pt, 🗣 locale:ru, 🗣 locale:zh, 🗣 locale:fil, 🗣 locale:el, 🗣 locale:id, 🗣 locale:sv, 🗣 locale:th, 🗣 locale:pl, 🗣 locale:hi, 🗣 locale:ar, 🗣 locale:ko, 🗣 locale:vi, 🗣 locale:tr, 🗣 locale:bn, 🗣 locale:fa_IR, 🗣 locale:nl, 🗣 locale:km, 🗣 locale:sl, 🗣 locale:uk, 🗣 locale:bs

#6738 Add Italian Spring Framework video course
  courses/free-courses-it.md
Labels: 🚀 ready to merge, 🗣 locale:it

#6732 Add `Git Cookbook` by Dennis Kaarsemaker
  books/free-programming-books-langs.md
Labels: 🚀 ready to merge, 🗣 locale:en
