Repository EbookFoundation/free-programming-books, pull requests merged in 2022-07, with the labels that each got.

#6896 docs(books): updated unavailable resource
  books/free-programming-books-subjects.md
Labels: 🚀 ready to merge, 🗣 locale:en, urlchecker

#6892 add new free-programming-interactive-tutorials in ru
  more/free-programming-interactive-tutorials-ru.md
Labels: 🚀 ready to merge, 🗣 locale:ru

#6834 chore: fully improve of english podcast/screencast listing
  casts/free-podcasts-screencasts-en.md
Labels: 🗣 locale:en, urlchecker

#6902 Add spanish podcasts by Carlos Blé Jurado
  casts/free-podcasts-screencasts-es.md
Labels: 🗣 locale:es

#6903 Add `Drupalízate` spanish podcast by Robert Menetray
  casts/free-podcasts-screencasts-es.md
Labels: 🗣 locale:es

#6906 add gulp.js resource to ar courses
  courses/free-courses-ar.md
Labels: linter error

#6895 docs(courses): fix italian course page
  courses/free-courses-it.md
Labels: 👀 Needs Review, 🗣 locale:it, urlchecker

#6907 docs(courses): add italian course
  courses/free-courses-it.md
Labels: 🚀 ready to merge, 🗣 locale:it

#6909 use danish lang code, not country. fixes #6908
  README.md
  books/free-programming-books-da.md
Labels: 🚀 ready to merge, 🗣 translations, 🗣 locale:da

#6890 docs(CONTRIBUTING): Apply #6878 to the rest of the CONTRIBUTING files
  docs/CONTRIBUTING-de.md
  docs/CONTRIBUTING-el.md
  docs/CONTRIBUTING-es.md
  docs/CONTRIBUTING-fa_IR.md
  docs/CONTRIBUTING-fil.md
  docs/CONTRIBUTING-fr.md
  docs/CONTRIBUTING-id.md
  docs/CONTRIBUTING-it.md
  docs/CONTRIBUTING-ko.md
  docs/CONTRIBUTING-pt_BR.md
  docs/CONTRIBUTING-ru.md
  docs/CONTRIBUTING-vi.md
  docs/CONTRIBUTING-zh.md
  docs/CONTRIBUTING-zh_TW.md
Labels: help wanted, 🚀 ready to merge, 🗣 translations, 🗣 locale:en, 🗣 locale:es, 🗣 locale:fr, 🗣 locale:de, 🗣 locale:it, 🗣 locale:pt, 🗣 locale:ru, 🗣 locale:zh, 🗣 locale:fil, 🗣 locale:el, 🗣 locale:ko, 🗣 locale:vi, 🗣 locale:fa_IR

#6930 Add CodeOfConduct-zh.md
  docs/CODE_OF_CONDUCT-zh.md
  docs/README.md
Labels: 🚀 ready to merge, 🗣 translations, 🗣 locale:zh

#6928 fix: update OWASP Testing Guide link to v4.2
  books/free-programming-books-subjects.md
Labels: 🚀 ready to merge, 🗣 locale:en, urlchecker

#6929 feat: Merge `Version Control Systems` into same section
  books/free-programming-books-langs.md
  books/free-programming-books-subjects.md
Labels: 🚀 ready to merge, 🗣 locale:en

#6923 Update free-courses-bn.md
  courses/free-courses-bn.md
Labels: 🚀 ready to merge, 🗣 locale:bn

#6935 docs(books): add 'Controllo di Versione con Subversion' to italian books
  books/free-programming-books-it.md
Labels: 🚀 ready to merge, 🗣 locale:it

#6937 add courses to Arabic courses page
  courses/free-courses-ar.md
Labels: 🚀 ready to merge, 🗣 locale:ar

#6936 Add FrontEnd Masters Guides
  books/free-programming-books-langs.md
  books/free-programming-books-subjects.md
Labels: waiting for changes, 🗣 locale:en

#6948 Add new courses for iOS
  courses/free-courses-en.md
Labels: 🚀 ready to merge, 🗣 locale:en

#6945 New Django Course!
  courses/free-courses-en.md
Labels: 🚀 ready to merge, 🗣 locale:en

#6950 Added a new course
  courses/free-courses-hi.md
Labels: 🚀 ready to merge, 🗣 locale:hi

#6953 docs(books): add 'Angular Tutorial' in english courses
  courses/free-courses-en.md
Labels: 🗣 locale:en

#6956 fix(books): free-programming-books-ko broken link
  books/free-programming-books-ko.md
Labels: question, help wanted, 🗣 locale:ko

#6955 fix(books): free-programming-books-pt_BR broken links
  books/free-programming-books-pt_BR.md
Labels: 🚀 ready to merge, 🗣 locale:pt, urlchecker

#6957 Adding A Complete Guide to Standard C++ Algorithms
  books/free-programming-books-langs.md
Labels: waiting for changes

#6960 added git and github course
  courses/free-courses-bn.md
Labels: 🚀 ready to merge, 🗣 locale:bn

#6863 Update free-courses-en.md
  courses/free-courses-en.md
Labels: 🚀 ready to merge, 🗣 locale:en

#6904 Adicionando tres playlists flutter
  courses/free-courses-pt_BR.md
Labels: 🚀 ready to merge, 🗣 locale:pt

#6965 fix(books): free-programming-books-fa_IR broken link
  books/free-programming-books-fa_IR.md
Labels: 🚀 ready to merge, 🗣 locale:fa_IR

#6966 fix(books): free-programming-books-fr broken links
  books/free-programming-books-fr.md
Labels: 🗣 locale:fr

#6961 chore: bump #6872. update node&react sources
  courses/free-courses-en.md
  courses/free-courses-vi.md
Labels: 🚀 ready to merge, 🗣 locale:en, 🗣 locale:vi

#6971 Adding Pascal language references to books
  books/free-programming-books-langs.md
Labels: waiting for changes, 🗣 locale:en

#6967 fix(books): free-programming-books-ru broken links
  books/free-programming-books-ru.md
Labels: 🗣 locale:ru

#6964 add new arabic courses
  courses/free-courses-ar.md
Labels: 🚀 ready to merge, 🗣 locale:ar

#6972 feat(podcast): add `Webificando` by Abel Fernandez & Robert Menetray
  casts/free-podcasts-screencasts-es.md
Labels: 🗣 locale:es

#6963 chore: merge and homogenize `HTML & CSS` sections across files
  books/free-programming-books-ar.md
  books/free-programming-books-az.md
  books/free-programming-books-cs.md
  books/free-programming-books-de.md
  books/free-programming-books-es.md
  books/free-programming-books-fa_IR.md
  books/free-programming-books-fr.md
  books/free-programming-books-hu.md
  books/free-programming-books-id.md
  books/free-programming-books-it.md
  books/free-programming-books-ko.md
  books/free-programming-books-langs.md
  books/free-programming-books-pl.md
  books/free-programming-books-pt_BR.md
  books/free-programming-books-pt_PT.md
  books/free-programming-books-ro.md
  books/free-programming-books-ru.md
  books/free-programming-books-ta.md
  books/free-programming-books-tr.md
  books/free-programming-books-uk.md
  books/free-programming-books-zh.md
  casts/free-podcasts-screencasts-en.md
  casts/free-podcasts-screencasts-pt_BR.md
  courses/free-courses-ar.md
  courses/free-courses-en.md
  courses/free-courses-fr.md
  courses/free-courses-id.md
  courses/free-courses-kk.md
  courses/free-courses-pl.md
  courses/free-courses-pt_BR.md
  courses/free-courses-ru.md
  courses/free-courses-si.md
  courses/free-courses-tr.md
  courses/free-courses-vi.md
  more/free-programming-cheatsheets.md
  more/free-programming-interactive-tutorials-en.md
  more/free-programming-interactive-tutorials-ja.md
  more/free-programming-playgrounds.md
Labels: 🚀 ready to merge, 🗣 locale:en, 🗣 locale:es, 🗣 locale:fr, 🗣 locale:de, 🗣 locale:it, 🗣 locale:pt, 🗣 locale:ru, 🗣 locale:zh, 🗣 locale:id, 🗣 locale:pl, 🗣 locale:ar, 🗣 locale:ko, 🗣 locale:vi, 🗣 locale:tr, 🗣 locale:fa_IR, 🗣 locale:uk, 🗣 locale:az, 🗣 locale:cs, 🗣 locale:hu, 🗣 locale:ro, 🗣 locale:ta, 🗣 locale:kk, 🗣 locale:si

#6975 fix(books): free-programming-books-tr broken links
  books/free-programming-books-tr.md
Labels: 🚀 ready to merge, 🗣 locale:tr

#6974 PULL_REQUEST_TEMPLATE: add clause for informative pr names
  .github/PULL_REQUEST_TEMPLATE.md
Labels: New Feature, 👥 discussion
