Repository EbookFoundation/free-programming-books, pull requests merged in 2022-01, with the labels that each got.

#6652 Add APL-related items
  books/free-programming-books-langs.md
  casts/free-podcasts-screencasts-en.md
  courses/free-courses-en.md
  courses/free-courses-fr.md
  more/free-programming-cheatsheets.md
  more/free-programming-playgrounds.md
  more/problem-sets-competitive-programming.md
Labels: waiting for changes

#6662 format: center repo badges
  README.md
Labels: conflicts

#6663 Adding Domain-Driven Design Reference
  books/free-programming-books-subjects.md
Labels: waiting for changes

#6664 Added New Compiler Resource to C++
  more/free-programming-playgrounds.md
Labels: waiting for changes, linter error

#6670 Add "ANSI Common Lisp Standard"
  books/free-programming-books-langs.md
Labels: ready to merge

#6673 Update .Net Url
  courses/free-courses-en.md
Labels: ready to merge

#6687 docs(courses): splitted resources from misc
  courses/free-courses-en.md
Labels: Needs Review

#6686 docs(books): solved two issues
  books/free-programming-books-subjects.md
Labels: Needs Review

#6677 fix(docs): Use Kramdown processor
  _config.yml
  docs/CODE_OF_CONDUCT-fa_IR.md
  docs/CONTRIBUTING-fa_IR.md
  docs/HOWTO-fa_IR.md
Labels: help wanted
