Repository EbookFoundation/free-programming-books, pull requests merged in 2022-10, with the labels that each got.

#7125 Add shell scripting tutorial
  courses/free-courses-en.md
Labels: :rocket: ready to merge, :speaking_head: locale:en

#7129 Add/code-of-conduct-th.md
  docs/CODE_OF_CONDUCT-th.md
  docs/README.md
Labels: :rocket: ready to merge, :speaking_head: locale:th

#7134 removed three broken links
  books/free-programming-books-ja.md
Labels: :rocket: ready to merge, :speaking_head: locale:jp, urlchecker

#7135 Added the swedish course "ProgSharp"
  README.md
  courses/free-courses-sv.md
Labels: :rocket: ready to merge, :speaking_head: locale:sv

#7140 Update free-courses-hi.md
  courses/free-courses-hi.md
Labels: :rocket: ready to merge, :speaking_head: locale:hi

#7142 Added Android Development and DevOps Bootcamp courses.
  courses/free-courses-en.md
Labels: :rocket: ready to merge, :speaking_head: locale:en

#7147 Add free course Thai language Javascript
  courses/free-courses-th.md
Labels: :rocket: ready to merge, :speaking_head: locale:th

#7150 Update free-podcasts-screencasts-en.md
  casts/free-podcasts-screencasts-en.md
Labels: :rocket: ready to merge, :speaking_head: locale:en

#7151 Update free-podcasts-screencasts-en.md
  casts/free-podcasts-screencasts-en.md
Labels: :rocket: ready to merge, :speaking_head: locale:en

#7152 Update free-courses-en.md
  courses/free-courses-en.md
Labels: :rocket: ready to merge, :speaking_head: locale:en

#7154 Add remote ruby podcast
  casts/free-podcasts-screencasts-en.md
Labels: :rocket: ready to merge

#7156 Fix broken links in spanish free programming books
  books/free-programming-books-es.md
Labels: :rocket: ready to merge, :speaking_head: locale:es, urlchecker

#7159 Update free-courses-ko.md
  courses/free-courses-ko.md
Labels: :rocket: ready to merge, :speaking_head: locale:ko

#7167 New Python 11 hour long video
  courses/free-courses-en.md
Labels: :rocket: ready to merge, :speaking_head: locale:en

#7168 Added a Bengali book on Data Science
  books/free-programming-books-bn.md
Labels: :rocket: ready to merge, :speaking_head: locale:bn

#7179 Update free-courses-pl.md
  courses/free-courses-pl.md
Labels: :rocket: ready to merge, :speaking_head: locale:pl

#7171 Update README.md
  README.md
Labels: :rocket: ready to merge, :speaking_head: locale:ar

#7174 Added cheatsheet for Fish Shell
  more/free-programming-cheatsheets.md
Labels: :rocket: ready to merge, :speaking_head: locale:en

#7181 Update podcast from indonesia
  casts/free-podcasts-screencasts-id.md
Labels: :rocket: ready to merge, :speaking_head: locale:id

#7182 add: free course learn reactjs
  courses/free-courses-id.md
Labels: :rocket: ready to merge, :speaking_head: locale:id

#7185 add golang video crash course
  courses/free-courses-en.md
Labels: :rocket: ready to merge, :speaking_head: locale:en

#7190 Added 'Atlassian Git Cheatsheet'
  more/free-programming-cheatsheets.md
Labels: :rocket: ready to merge, :speaking_head: locale:en

#7202 Fix broken link to docker cheatsheet
  more/free-programming-cheatsheets.md
Labels: :rocket: ready to merge, :speaking_head: locale:en

#7203 Remove broken link to es6 interactive tutotial
  more/free-programming-interactive-tutorials-en.md
Labels: :rocket: ready to merge, :speaking_head: locale:en

#7206 Update free-courses-hi.md
  courses/free-courses-hi.md
Labels: :rocket: ready to merge, :speaking_head: locale:hi

#7207 add tailwind-play to free-programming-playgrounds
  more/free-programming-playgrounds.md
Labels: :rocket: ready to merge, :speaking_head: locale:en

#7209 Update free-courses-ko.md
  courses/free-courses-ko.md
Labels: :rocket: ready to merge, :speaking_head: locale:ko

#7210 Add Networking! ACK! book by Julia Evans
  books/free-programming-books-subjects.md
Labels: :rocket: ready to merge, :speaking_head: locale:en

#7213 Kotlin git recources
  courses/free-courses-en.md
Labels: :rocket: ready to merge, :speaking_head: locale:en

#7216 Fix the course links to new versions
  courses/free-courses-ko.md
Labels: :rocket: ready to merge, :speaking_head: locale:ko

#7218 Add frontend armory react course
  courses/free-courses-en.md
Labels: :rocket: ready to merge, :speaking_head: locale:en

#7137 Update free-courses-hi.md
  courses/free-courses-hi.md
Labels: :rocket: ready to merge, :speaking_head: locale:hi

#7148 Add W3Schools' XML tutorial
  more/free-programming-interactive-tutorials-en.md
Labels: :rocket: ready to merge, :speaking_head: locale:en

#7162 Update free-podcasts-screencasts-en.md
  casts/free-podcasts-screencasts-en.md
Labels: :rocket: ready to merge, :speaking_head: locale:en

#7132 Updated Django cheat sheets
  more/free-programming-cheatsheets.md
Labels: :rocket: ready to merge, :speaking_head: locale:en

#7138 docker fast course in pt-br
  courses/free-courses-pt_BR.md
Labels: :rocket: ready to merge, :speaking_head: locale:pt

#7145 Update free-courses-hi.md
  courses/free-courses-hi.md
Labels: :rocket: ready to merge, :speaking_head: locale:en

#7166 Add free c# programming online book
  books/free-programming-books-th.md
Labels: :rocket: ready to merge, :speaking_head: locale:th

#7183 Added a new pandas book (HTML)
  books/free-programming-books-langs.md
Labels: :rocket: ready to merge, :speaking_head: locale:en

#7212 Add react ressources
  courses/free-courses-en.md
Labels: :rocket: ready to merge, :speaking_head: locale:en

#7220 Added New Django Rest Framework PDF
  books/free-programming-books-langs.md
Labels: :rocket: ready to merge, :speaking_head: locale:en

#7224 added ultimate topics list for competitive programming
  more/problem-sets-competitive-programming.md
Labels: :rocket: ready to merge, :speaking_head: locale:en

#7227 feat: add machine learning webinar indonesia
  courses/free-courses-id.md
Labels: :rocket: ready to merge, :speaking_head: locale:id

#7253 Corrections in the text
  docs/CODE_OF_CONDUCT-es.md
Labels: :rocket: ready to merge, :speaking_head: translations, :speaking_head: locale:es

#7264 Add JavaScript Course Tutorial
  courses/free-courses-hi.md
Labels: :rocket: ready to merge, :speaking_head: locale:hi

#7265 New resources
  courses/free-courses-hi.md
Labels: :rocket: ready to merge, :speaking_head: locale:hi

#7268 Added MongoDB Bengali Course Tutorial
  courses/free-courses-bn.md
Labels: :rocket: ready to merge, :speaking_head: locale:bn

#7269 Add 'Einführung in das Programmieren mit C# 9.0' by Uni Trier
  books/free-programming-books-de.md
Labels: :rocket: ready to merge, :speaking_head: locale:de

#7271 Broken Links Fix for #6942
  books/free-programming-books-hu.md
Labels: :rocket: ready to merge, :speaking_head: locale:hu, urlchecker

#7270 Add 'Einführung in das Programmieren mit Java' by Uni Trier
  books/free-programming-books-de.md
Labels: :rocket: ready to merge, :speaking_head: locale:de

#7274 Add: Beginners typescript course (Matt Pocock)
  courses/free-courses-en.md
Labels: :rocket: ready to merge, :speaking_head: locale:en

#7275 Fix the course links to new versions
  courses/free-courses-ko.md
Labels: :rocket: ready to merge, :speaking_head: locale:ko

#7276 Add a Java Spring Boot and a Kotlin free courses in pt-BR
  courses/free-courses-pt_BR.md
Labels: :rocket: ready to merge, :speaking_head: locale:pt

#7308 duplicate course was added in free-courses-hi.md(cpp section), so i removed it
  courses/free-courses-hi.md
Labels: :rocket: ready to merge, :speaking_head: locale:hi

#7278 Update problem-sets-competitive-programming.md
  more/problem-sets-competitive-programming.md
Labels: question, :speaking_head: locale:en

#7336 Broken links
  courses/free-courses-en.md
  more/problem-sets-competitive-programming.md
Labels: linter error

#7273 Add free course on Spark
  courses/free-courses-en.md
Labels: waiting for changes, :speaking_head: locale:en

#7232 Added C/C++ book in Ukrainian
  books/free-programming-books-uk.md
Labels: :rocket: ready to merge, :speaking_head: locale:uk

#7263 Add Vue.js Course
  courses/free-courses-hi.md
Labels: :rocket: ready to merge, :speaking_head: locale:hi

#7277 ko translation modified in more native way
  courses/free-courses-ko.md
  docs/CONTRIBUTING-ko.md
Labels: :rocket: ready to merge, :speaking_head: locale:ko

#7334 Update free-programming-books-id.md
  books/free-programming-books-id.md
Labels: :rocket: ready to merge, :speaking_head: locale:id

#7349 added two courses in git and github in free-courses-hi.md
  courses/free-courses-hi.md
Labels: :rocket: ready to merge, :speaking_head: locale:hi

#7361 Added NodeJS Bengali Course Tutorial
  courses/free-courses-bn.md
Labels: :rocket: ready to merge, :speaking_head: locale:bn

#7368 Remove broken link for Symfony 5.0 in Arabic
  books/free-programming-books-ar.md
Labels: :rocket: ready to merge, :speaking_head: locale:ar

#7372 Add Xamarin.Forms Notes for professionals
  books/free-programming-books-langs.md
Labels: waiting for changes, :rocket: ready to merge, :speaking_head: locale:en

#7378 add beginner kotlin course
  courses/free-courses-en.md
Labels: :rocket: ready to merge, :speaking_head: locale:en

#7379 Add JavaScript in 14 minutes interactive tutorial by Jeremy Thomas
  more/free-programming-interactive-tutorials-en.md
Labels: :rocket: ready to merge, :speaking_head: locale:en

#7284 Adds a new course under the **RUST** section
  courses/free-courses-en.md
Labels: waiting for changes, :speaking_head: locale:en

#7286 Add Free JS Book check_urls=free-programming-bookslangs.md
  books/free-programming-books-langs.md
Labels: waiting for changes, :speaking_head: locale:en

#7350 Added a youtube video javascript tutorial in Indonesian
  books/free-programming-books-id.md
Labels: waiting for changes, :speaking_head: locale:id

#7366 Added Udemy HTML Course
  courses/free-courses-en.md
Labels: question, :speaking_head: locale:en

#7375 Giovana np1 patch 1
  books/free-programming-books-pt_BR.md
  casts/free-podcasts-screencasts-pt_BR.md
  courses/free-courses-en.md
Labels: waiting for changes, :speaking_head: locale:en, :speaking_head: locale:pt

#7341 Update free-courses-en.md
  courses/free-courses-en.md
Labels: :rocket: ready to merge, :speaking_head: locale:en

#7365 Add DevOps Course
  courses/free-courses-en.md
Labels: :rocket: ready to merge, :speaking_head: locale:en

#7217 Newcourses
  courses/free-courses-en.md
  courses/free-courses-hi.md
Labels: waiting for changes, :speaking_head: locale:en, :speaking_head: locale:hi

#7298 Added Neso Academy PlayList on Operating Systems
  courses/free-courses-en.md
Labels: waiting for changes

#7309 Removed broken links
  books/free-programming-books-de.md
Labels: waiting for changes, :speaking_head: locale:de, urlchecker

#7352 Added german books by Rheinwerk Computing:
  books/free-programming-books-de.md
Labels: waiting for changes, :speaking_head: locale:de

#7371 Added TypeScript and Docker Bengali Course Tutorial
  courses/free-courses-bn.md
Labels: waiting for changes

#7382 Added JavaScript, PHP, Go and Swift books
  books/free-programming-books-langs.md
Labels: :rocket: ready to merge, :speaking_head: locale:en

#7396 Added codewithharry Mongodb cheat sheet
  more/free-programming-cheatsheets.md
Labels: :rocket: ready to merge, :speaking_head: locale:en

#7406 docs(HOWTO): Translated alot of Text in Hindi and added few links
  docs/HOWTO-hi.md
Labels: :rocket: ready to merge, :speaking_head: translations, :speaking_head: locale:hi

#7385 Replace the broken course for wordpress
  courses/free-courses-es.md
Labels: waiting for changes

#7461 Add translation for Swedish in docs: CONTRIBUTING & CODE_OF_CONDUCT
  docs/CODE_OF_CONDUCT-sv.md
  docs/CONTRIBUTING-sv.md
  docs/HOWTO-sv.md
  docs/README.md
Labels: :speaking_head: translations, :speaking_head: locale:sv

#7387 Added Free and Certified Python course in Hindi by Coding Blocks Junior
  courses/free-courses-hi.md
Labels: waiting for changes

#7388 Added a free Robotics course in English
  courses/free-courses-en.md
Labels: waiting for changes

#7408 Add bootstrap books in free-programming-books-id.md
  books/free-programming-books-id.md
Labels: waiting for changes, :speaking_head: locale:id

#7411 ASP.Net DevOps pipeline book
  books/free-programming-books-subjects.md
Labels: question

#7423 Modified hindi courses
  courses/free-courses-hi.md
Labels: waiting for changes

#7424 Added an eBook on learning arduino
  books/free-programming-books-langs.md
Labels: waiting for changes

#7433 Update free-programming-interactive-tutorials-en.md
  more/free-programming-interactive-tutorials-en.md
Labels: waiting for changes

#7437 Added Amazon Web Service (AWS) Arabic Playlist
  courses/free-courses-ar.md
Labels: waiting for changes

#7442 Added a new Course under the Algorithms sections
  courses/free-courses-hi.md
Labels: waiting for changes

#7302 Add course php
  courses/free-courses-pl.md
Labels: :rocket: ready to merge, :speaking_head: locale:pl

#7310 added Artificial intelligence heading and one course in free-courses-hi.md
  courses/free-courses-hi.md
Labels: :rocket: ready to merge, :speaking_head: locale:hi

#7312 added maths section and numberous courses underit, different headings for different topics in free-courses-hi.md
  courses/free-courses-hi.md
Labels: :rocket: ready to merge, :speaking_head: locale:hi

#7315 added SortingAlgos in Algorithm in free-courses-hi.md
  courses/free-courses-hi.md
Labels: :rocket: ready to merge, :speaking_head: locale:hi

#7319 added Digital Electronics in free-courses-en.med
  courses/free-courses-en.md
Labels: :rocket: ready to merge, :speaking_head: locale:en

#7355 added c-sharp heading and two of its courses in free-courses-hi.md
  courses/free-courses-hi.md
Labels: :rocket: ready to merge, :speaking_head: locale:hi

#7393 Added gfg c-plus-plus tutorial
  more/free-programming-interactive-tutorials-en.md
Labels: :rocket: ready to merge, :speaking_head: locale:en

#7409 Added 3 new courses
  courses/free-courses-en.md
  courses/free-courses-hi.md
Labels: :rocket: ready to merge, :speaking_head: locale:en, :speaking_head: locale:hi

#7420 Added youtube playlists for React and Flask
  courses/free-courses-en.md
Labels: :rocket: ready to merge, :speaking_head: locale:en

#7451 Added Compiler Design Course
  courses/free-courses-en.md
Labels: :rocket: ready to merge, :speaking_head: locale:en

#7478 Added Free Certified Course on Game Development
  courses/free-courses-en.md
Labels: :rocket: ready to merge, :speaking_head: locale:en

#7479 Added new Low Poly Art Design Game Dev Course for Beginners
  courses/free-courses-en.md
Labels: :rocket: ready to merge, :speaking_head: locale:en

#7480 Added a new Hindi Course on App Dev for Students
  courses/free-courses-hi.md
Labels: :rocket: ready to merge, :speaking_head: locale:hi

#7482 Added a new course on Web Dev in Hindi
  courses/free-courses-hi.md
Labels: :rocket: ready to merge, :speaking_head: locale:hi

#7449 add cs50 introduction to computer science
  courses/free-courses-en.md
Labels: waiting for changes

#7348 Added Golang Language Courses
  courses/free-courses-hi.md
Labels: conflicts, :speaking_head: locale:hi

#7219 Add free ES screencast and HTML resources
  casts/free-podcasts-screencasts-es.md
Labels: :rocket: ready to merge, :speaking_head: locale:es

#7305 feat: added nextjs cheatsheet and go cheatsheet
  more/free-programming-cheatsheets.md
Labels: :rocket: ready to merge, :speaking_head: locale:en

#7468 Update free-courses-en.md
  courses/free-courses-en.md
Labels: :rocket: ready to merge, :speaking_head: locale:en

#7491 Added Compilers Design Course
  courses/free-courses-en.md
Labels: :rocket: ready to merge, :speaking_head: locale:en

#7492 Added Data Structure and Algorithm Course
  courses/free-courses-en.md
Labels: :rocket: ready to merge, :speaking_head: locale:en

#7316 added Operating systems and two courses in free-courses-hi.md
  courses/free-courses-hi.md
Labels: waiting for changes, conflicts, :speaking_head: locale:hi

#7318 added DatabaseSystems in free-course-hi.nd and two courses in it
  courses/free-courses-hi.md
Labels: waiting for changes, :speaking_head: locale:hi

#7484 Added The Odin Project Course
  courses/free-courses-en.md
Labels: waiting for changes, :speaking_head: locale:en

#7501 Added SQl Tamil Playlist New PR
  courses/free-courses-ta.md
Labels: waiting for changes

#7503 Adding Playlist Explaining Sliding Window Algorithm
  courses/free-courses-hi.md
Labels: waiting for changes

#7516 added android course in free-courses-hi.md
  courses/free-courses-hi.md
Labels: waiting for changes

#7520 added cp heading and courses in free-courses-hi.md
  courses/free-courses-hi.md
Labels: waiting for changes

#7521 #added computer networking course
  courses/free-courses-en.md
Labels: waiting for changes

#7311 added computer networks in index and two course in free-courses-hi.md
  courses/free-courses-hi.md
Labels: :rocket: ready to merge, :speaking_head: locale:hi

#7342 Added two Courses (C programming and Github contribution)
  courses/free-courses-hi.md
Labels: :rocket: ready to merge, :speaking_head: locale:hi

#7370 feat: add codecademy typescript course
  courses/free-courses-en.md
Labels: :rocket: ready to merge, :speaking_head: locale:en

#7377 Docker broken links
  more/free-programming-cheatsheets.md
Labels: :rocket: ready to merge, :speaking_head: locale:en

#7419 Added React.js Course By Mosh
  courses/free-courses-en.md
Labels: :rocket: ready to merge, :speaking_head: locale:en

#7455 Add Italian Javascript course
  courses/free-courses-it.md
Labels: :rocket: ready to merge, :speaking_head: locale:it

#7457 Added three Data Structure and Algorithms course in Free Courses in English
  courses/free-courses-en.md
Labels: :rocket: ready to merge, :speaking_head: locale:en

#7494 Removed some inaccessible links in programming books of Chinese
  books/free-programming-books-zh.md
Labels: :rocket: ready to merge, :speaking_head: locale:zh, urlchecker

#7496 Add free courses bahasa Indonesia "Belajar HTML 5"
  courses/free-courses-id.md
Labels: :rocket: ready to merge, :speaking_head: locale:hi

#7517 Added new free courses
  courses/free-courses-en.md
Labels: :rocket: ready to merge, :speaking_head: locale:en

#7522 Added bengali textbook for C++ progamming
  books/free-programming-books-bn.md
Labels: :rocket: ready to merge, :speaking_head: locale:bn

#7533 Competitive programming course Added
  courses/free-courses-hi.md
Labels: :rocket: ready to merge, :speaking_head: locale:hi

#7541 Nepali course
  README.md
  courses/free-courses-ne.md
Labels: :rocket: ready to merge, :speaking_head: locale:ne

#7542 Added DBMS Course
  courses/free-courses-en.md
Labels: :rocket: ready to merge, :speaking_head: locale:en

#7592 Add Polish book about C++
  books/free-programming-books-pl.md
Labels: :rocket: ready to merge, :speaking_head: locale:pl

#7594 Added resource section for telugu books
  README.md
  books/free-programming-books-te.md
Labels: :rocket: ready to merge, :speaking_head: locale:te

#7596 Add JS playground in zh_cn
  more/free-programming-playgrounds-zh.md
Labels: :rocket: ready to merge

#7599 Add Git interactive tutorial in zh_cn
  books/free-programming-books-zh.md
  more/free-programming-interactive-tutorials-zh.md
Labels: :rocket: ready to merge, :speaking_head: locale:zh

#7605 Added HOWTO-te.md for TELUGU
  docs/HOWTO-te.md
  docs/README.md
Labels: :rocket: ready to merge, :speaking_head: translations, :speaking_head: locale:te

#7607 Add Polish book about LaTeX
  books/free-programming-books-pl.md
Labels: :rocket: ready to merge, :speaking_head: locale:pl

#7448 Added new bootcamp course on Problem Solving, Python Programming
  courses/free-courses-en.md
Labels: :speaking_head: locale:en

#7508 Tamil Books - Updated the links to latest blog and fixed existing bro…
  books/free-programming-books-ta.md
Labels: waiting for changes, :speaking_head: locale:ta

#7509 Added the The Official Raspberry Pi Handbook 2023[pdf]
  books/free-programming-books-langs.md
Labels: :rocket: ready to merge, :speaking_head: locale:en

#7571 Add Building Microservices architecture with ASP.NET to Courses
  courses/free-courses-en.md
Labels: :rocket: ready to merge, :speaking_head: locale:en

#7584 updated free iOS book
  books/free-programming-books-langs.md
Labels: :rocket: ready to merge, :speaking_head: locale:en

#7624 hari70a add sass cheatsheet
  more/free-programming-cheatsheets.md
Labels: :rocket: ready to merge, :speaking_head: locale:en

#7589 Added a course in english "CS250: Python for Data Science" from Saylor.org. Please merge.
  courses/free-courses-en.md
Labels: :speaking_head: locale:en

#7611 Scratch Programming in Bangla course added
  courses/free-courses-bn.md
Labels: waiting for changes
