Repository EbookFoundation/free-programming-books, pull requests merged in 2022-09, with the labels that each got.

#7034 fix: homogenize authoring format and place
  books/free-programming-books-ar.md
  books/free-programming-books-de.md
  books/free-programming-books-es.md
  books/free-programming-books-fa_IR.md
  books/free-programming-books-fr.md
  books/free-programming-books-hu.md
  books/free-programming-books-id.md
  books/free-programming-books-it.md
  books/free-programming-books-ja.md
  books/free-programming-books-ko.md
  books/free-programming-books-langs.md
  books/free-programming-books-my.md
  books/free-programming-books-pl.md
  books/free-programming-books-pt_BR.md
  books/free-programming-books-pt_PT.md
  books/free-programming-books-ru.md
  books/free-programming-books-subjects.md
  books/free-programming-books-th.md
  books/free-programming-books-tr.md
  books/free-programming-books-vi.md
  books/free-programming-books-zh.md
  casts/free-podcasts-screencasts-ar.md
  casts/free-podcasts-screencasts-en.md
  casts/free-podcasts-screencasts-pt_PT.md
  courses/free-courses-en.md
  courses/free-courses-es.md
  courses/free-courses-fr.md
  courses/free-courses-it.md
  courses/free-courses-pt_BR.md
  more/free-programming-interactive-tutorials-en.md
Labels: 🗣 locale:en, 🗣 locale:es, 🗣 locale:fr, 🗣 locale:de, 🗣 locale:it, 🗣 locale:pt, 🗣 locale:zh, 🗣 locale:jp, 🗣 locale:id, 🗣 locale:th, 🗣 locale:pl, 🗣 locale:ar, 🗣 locale:ko, 🗣 locale:tr, 🗣 locale:fa_IR, 🗣 locale:hu

#7052 chore: remove `Scaler Topics`'s dups from books
  books/free-programming-books-langs.md
Labels: 🗣 locale:en

#7063 Update free-programming-books-tr.md
  books/free-programming-books-tr.md
Labels: :rocket: ready to merge, :speaking_head: locale:tr

#7068 Fix the link for Modern C
  books/free-programming-books-langs.md
Labels: waiting for changes, :speaking_head: locale:en, urlchecker

#7065 chore!: join `IDE and editors` into same section
  books/free-programming-books-es.md
  books/free-programming-books-fr.md
  books/free-programming-books-hu.md
  books/free-programming-books-id.md
  books/free-programming-books-ja.md
  books/free-programming-books-langs.md
  books/free-programming-books-pl.md
  books/free-programming-books-pt_BR.md
  books/free-programming-books-ru.md
  books/free-programming-books-subjects.md
  books/free-programming-books-zh.md
  casts/free-podcasts-screencasts-en.md
  courses/free-courses-bn.md
  courses/free-courses-pt_BR.md
  courses/free-courses-tr.md
  more/free-programming-cheatsheets.md
  more/free-programming-interactive-tutorials-en.md
Labels: :speaking_head: locale:en, :speaking_head: locale:es, :speaking_head: locale:fr, :speaking_head: locale:pt, :speaking_head: locale:ru, :speaking_head: locale:zh, :speaking_head: locale:jp, :speaking_head: locale:id, :speaking_head: locale:tr, :speaking_head: locale:bn

#7053 ci(stale): create `stale.yml` workflow
  .github/workflows/stale.yml
Labels: New Feature, :busts_in_silhouette: discussion, :rocket: ready to merge, 🤖 automation

#7071 Update go gooks
  books/free-programming-books-ko.md
Labels: :rocket: ready to merge, :speaking_head: locale:ko

#6917 add Vue.js `sariasan.com` free full lessons
  courses/free-courses-fa_IR.md
Labels: :rocket: ready to merge, :speaking_head: locale:fa_IR

#7056 ci(pinner): Create `issues-pinner.yml` workflow
  .github/workflows/issues-pinner.yml
Labels: New Feature, :rocket: ready to merge, 🤖 automation

#7074 chore: update `agi.mit.edu` by Lex Fridman resource
  courses/free-courses-en.md
Labels: :speaking_head: locale:en, urlchecker

#7078 [books-ar] The section is named `Scratch` in the rest of files
  books/free-programming-books-ar.md
Labels: :rocket: ready to merge, :speaking_head: locale:ar

#7083 Add 'OCaml from the very beginning' book & OCaml playground
  books/free-programming-books-langs.md
  more/free-programming-playgrounds.md
Labels: :rocket: ready to merge, :speaking_head: locale:en

#7082 add & update arabic course
  courses/free-courses-ar.md
Labels: :rocket: ready to merge, :speaking_head: locale:ar

#7081 Add Docker course playlist by Robert Silva to `free-courses-pt_BR.md`
  courses/free-courses-pt_BR.md
Labels: :rocket: ready to merge, :speaking_head: locale:pt

#7088 Update free-programming-cheatsheets.md
  more/free-programming-cheatsheets.md
Labels: :rocket: ready to merge, :speaking_head: locale:es

#7090 improve resources found fixing EbookFoundation/free-programming-books-parser#8
  books/free-programming-books-fa_IR.md
  books/free-programming-books-langs.md
  books/free-programming-books-ru.md
  books/free-programming-books-zh.md
  casts/free-podcasts-screencasts-en.md
Labels: :speaking_head: locale:en, :speaking_head: locale:ru, :speaking_head: locale:zh, :speaking_head: locale:fa_IR

#7084 chore: improve info of Git & SVN books
  books/free-programming-books-cs.md
  books/free-programming-books-de.md
  books/free-programming-books-es.md
  books/free-programming-books-fr.md
  books/free-programming-books-id.md
  books/free-programming-books-it.md
  books/free-programming-books-ja.md
  books/free-programming-books-ko.md
  books/free-programming-books-pl.md
  books/free-programming-books-pt_BR.md
  books/free-programming-books-ru.md
  books/free-programming-books-subjects.md
  books/free-programming-books-tr.md
  books/free-programming-books-zh.md
Labels: :rocket: ready to merge, :speaking_head: locale:en, :speaking_head: locale:es, :speaking_head: locale:fr, :speaking_head: locale:de, :speaking_head: locale:it, :speaking_head: locale:pt, :speaking_head: locale:ru, :speaking_head: locale:zh, :speaking_head: locale:id, :speaking_head: locale:pl, :speaking_head: locale:ko, :speaking_head: locale:tr, :speaking_head: locale:cs

#7092 Remove Curso do React Native implementando CRUD
  courses/free-courses-pt_BR.md
Labels: :rocket: ready to merge

#7094 fix: format resources according guidelines
  books/free-programming-books-fa_IR.md
  books/free-programming-books-ru.md
  books/free-programming-books-zh.md
Labels: :speaking_head: locale:ru, :speaking_head: locale:zh, :speaking_head: locale:fa_IR

#7095 Added a new React cheat sheet resource
  more/free-programming-cheatsheets.md
Labels: :rocket: ready to merge, :speaking_head: locale:en

#7096 fix: refine concurrency policy of `check-urls.yml` workflow
  .github/workflows/check-urls.yml
Labels: :bug: BUG, 🤖 automation

#7093 fix: escape markdown in resources titles/links
  casts/free-podcasts-screencasts-en.md
Labels: :speaking_head: locale:en

#7098 Add Curso de Programação Lua
  courses/free-courses-pt_BR.md
Labels: :rocket: ready to merge, :speaking_head: locale:pt

#7059 fix: `check-url` report crashes on empty changed files
  .github/actions/awesomebot-gh-summary-action/action.yml
Labels: urlchecker, 🤖 automation

#7099 Add rust book in free-programming-books-pt_BR and author name of The Rust Programming Language in free-programming-books-langs
  books/free-programming-books-langs.md
  books/free-programming-books-pt_BR.md
Labels: :rocket: ready to merge, :speaking_head: locale:en, :speaking_head: locale:pt

#7100 fix: translator role abbr is `trl.:` not `trad.:`
  books/free-programming-books-tr.md
Labels: :rocket: ready to merge, :speaking_head: locale:tr

#7097 chore(books-es): complete resource creators
  books/free-programming-books-es.md
Labels: :speaking_head: locale:es

#7110 Add 'Linux IP Stacks Commentary - Web Edition'
  books/free-programming-books-subjects.md
Labels: :rocket: ready to merge, :speaking_head: locale:en

#7102 docs(CONTRIBUTING): complete creators guidelines with relator terms
  docs/CONTRIBUTING-de.md
  docs/CONTRIBUTING-el.md
  docs/CONTRIBUTING-es.md
  docs/CONTRIBUTING-fa_IR.md
  docs/CONTRIBUTING-fil.md
  docs/CONTRIBUTING-fr.md
  docs/CONTRIBUTING-id.md
  docs/CONTRIBUTING-it.md
  docs/CONTRIBUTING-ko.md
  docs/CONTRIBUTING-pt_BR.md
  docs/CONTRIBUTING-ru.md
  docs/CONTRIBUTING-vi.md
  docs/CONTRIBUTING-zh.md
  docs/CONTRIBUTING-zh_TW.md
  docs/CONTRIBUTING.md
Labels: New Feature, :speaking_head: translations, :speaking_head: locale:en, :speaking_head: locale:es, :speaking_head: locale:fr, :speaking_head: locale:de, :speaking_head: locale:it, :speaking_head: locale:pt, :speaking_head: locale:ru, :speaking_head: locale:zh, :speaking_head: locale:fil, :speaking_head: locale:el, :speaking_head: locale:id, :speaking_head: locale:ko, :speaking_head: locale:vi, :speaking_head: locale:fa_IR, :speaking_head: locale:et
