Repository EbookFoundation/free-programming-books, pull requests merged in 2023-02, with the labels that each got.

#9278 React Tutorial
  courses/free-courses-en.md
Labels: waiting for changes

#9287 security: `set-output` cmd deprecated. Use `$GITHUB_OUTPUT` env file
  .github/actions/awesomebot-gh-summary-action/action.yml
  .github/workflows/check-urls.yml
  .github/workflows/detect-conflicting-prs.yml
  .github/workflows/stale.yml
Labels: :eyes: Needs Review

#7060 ci(check-urls): use a matrix to speed-up execution
  .github/workflows/check-urls.yml
Labels: help wanted, :eyes: Needs Review, urlchecker, 🤖 automation
