Repository EbookFoundation/free-programming-books, pull requests merged in 2023-11, with the labels that each got.

#10931 add Feature Engineering book and Ethereum Blockchain Developer course
  books/free-programming-books-subjects.md
  courses/free-courses-en.md
Labels: waiting for changes

#10917 Update free-courses-en.md
  courses/free-courses-en.md
Labels: waiting for changes

#10901 Included Database Management Courses
  courses/free-courses-en.md
  courses/free-courses-hi.md
Labels: waiting for changes

#10932 Add missing creators in free-courses-fr.md
  courses/free-courses-fr.md
Labels: waiting for changes

#10896 Update free-programming-books-langs.md
  books/free-programming-books-langs.md
Labels: waiting for changes

#10887 Updated links for An Introduction to Statistical Learning
  books/free-programming-books-langs.md
  more/problem-sets-competitive-programming.md
Labels: waiting for changes

#10943 Add Italian course about Cryptography
  courses/free-courses-it.md
Labels: :rocket: ready to merge

#10946 Added an android course
  courses/free-courses-ur.md
Labels: :rocket: ready to merge

#10949 Added an android course
  courses/free-courses-ur.md
Labels: :rocket: ready to merge

#10947 Added a book for data structures and algorithms
  books/free-programming-books-subjects.md
Labels: waiting for changes

#10940 feat: added flutter resources
  courses/free-courses-en.md
Labels: question

#10761 added author names to 2 courses with same title, different authors
  courses/free-courses-es.md
Labels: waiting for changes

#10955 Adding two slovak books about Linux
  books/free-programming-books-sk.md
Labels: waiting for changes

#10958 Patch1
  courses/free-courses-ur.md
Labels: waiting for changes

#9628 Guide to Discrete Mathematics Book Add
  books/free-programming-books-subjects.md
Labels: :rocket: ready to merge

#10970 Dart Bangla Tutorial Added
  courses/free-courses-bn.md
Labels: :rocket: ready to merge

#10964 [Changes made] Add MySQL for Developers course
  courses/free-courses-en.md
Labels: waiting for changes

#9431 Update free-programming-books-fa_IR.md
  books/free-programming-books-fa_IR.md
Labels: stale

#9492 Update free-podcasts-screencasts-tr.md
  casts/free-podcasts-screencasts-tr.md
Labels: waiting for changes

#10941 Add CSS handbook
  books/free-programming-books-langs.md
Labels: question, :rocket: ready to merge

#10975 Mongo DB Tutorial Updated
  courses/free-courses-bn.md
Labels: :rocket: ready to merge

#10973 Add Python book in Armenian language
  README.md
  books/free-programming-books-hy.md
Labels: :rocket: ready to merge

#10974 Patch6
  courses/free-courses-en.md
  courses/free-courses-hi.md
Labels: :rocket: ready to merge

#9498 Update free-programming-playgrounds.md
  more/free-programming-playgrounds.md
Labels: waiting for changes

#9610 Update free-courses-hi.md
  courses/free-courses-hi.md
Labels: waiting for changes

#9743 Swapped 1.87 and 1.88 as shown. Added new course to free-courses-tr.md
  courses/free-courses-tr.md
Labels: waiting for changes

#9966 Added Japanese Translation of 3 md files (japanese review requested)
  docs/CODE_OF_CONDUCT-ja.md
  docs/CONTRIBUTING-ja.md
  docs/HOWTO-ja.md
  docs/README.md
Labels: help wanted, :speaking_head: locale:ja

#10979 Add WP Theme Development Playlist (changes made)
  courses/free-courses-bn.md
Labels: :rocket: ready to merge, changes made

#10110 React Native in Hindi
  courses/free-courses-hi.md
Labels: waiting for changes

#10245 Update free-courses-hi.md
  courses/free-courses-hi.md
Labels: waiting for changes

#10120 2 spanish courses
  courses/free-courses-es.md
Labels: waiting for changes

#10325 add framer motion resources
  courses/free-courses-en.md
Labels: waiting for changes

#10380 Added courses for Bun Js in free-courses-en.md
  courses/free-courses-en.md
Labels: waiting for changes

#10433 Add Introductory Database Book - PTBR
  books/free-programming-books-pt_BR.md
Labels: waiting for changes

#10465 Update free-courses-ar.md
  courses/free-courses-ar.md
Labels: waiting for changes

#10483 Update free-courses-hi.md
  courses/free-courses-hi.md
Labels: waiting for changes

#10572 Update free-podcasts-screencasts-ru.md
  casts/free-podcasts-screencasts-ru.md
Labels: waiting for changes

#10534 Course10
  courses/free-courses-kn.md
Labels: waiting for changes

#10611 Update free-programming-interactive-tutorials-en.md
  more/free-programming-interactive-tutorials-en.md
Labels: waiting for changes

#10617 Add PAIP to AI subject
  books/free-programming-books-subjects.md
Labels: waiting for changes

#10660 Update free-programming-books-fr.md
  books/free-programming-books-fr.md
Labels: waiting for changes

#10711 Vim Playground Added
  more/free-programming-playgrounds.md
Labels: waiting for changes

#10757 Updated free-programming-books-sr.md withi Singidunum University books
  books/free-programming-books-sr.md
Labels: waiting for changes

#10721 Update free-courses-en.md
  courses/free-courses-en.md
Labels: needs approval

#10717 Update free-courses-ar.md
  courses/free-courses-ar.md
Labels: needs approval

#10417 Code of Conduct for Marathi language added . (language review requested)
  docs/CODE_OF_CONDUCT-mr.md
  docs/README.md
Labels: help wanted, keep

#10766 Added Content to Learn Astro
  courses/free-courses-en.md
Labels: waiting for changes

#10834 Update README.md
  README.md
Labels: waiting for changes

#10892 Updated the title of playlist with the creator' name and institute as mentioned officially
  courses/free-courses-en.md
Labels: waiting for changes

#10923 Add algorithm playground
  more/free-programming-playgrounds.md
Labels: waiting for changes

#10965 Add the first course of Rust in pt-BR
  courses/free-courses-pt_BR.md
Labels: waiting for changes

#10963 Addition: Design Course
  courses/free-courses-en.md
  more/free-programming-cheatsheets.md
Labels: waiting for changes

#9534 Added Jadi Lpic-1 Course
  courses/free-courses-fa_IR.md
Labels: waiting for changes

#9598 feat: added web development free courses for beginners
  courses/free-courses-en.md
Labels: waiting for changes

#9867 Update free-courses-hi.md
  courses/free-courses-hi.md
Labels: waiting for changes

#9886 I added a Javascript e-book in the Bengali language.
  books/free-programming-books-bn.md
Labels: waiting for changes

#9925 nepali courses
  courses/free-courses-ne.md
Labels: waiting for changes

#10039 (changes made) Added course: OSCP prep (security)
  courses/free-courses-en.md
Labels: waiting for changes

#10494 Update free-courses-en.md - Added machine learning video link , Hacker's guide to model
  courses/free-courses-en.md
Labels: waiting for changes

#10437 Added new courses , a MOOC site, and a programming playground
  courses/free-courses-en.md
  more/free-programming-playgrounds.md
Labels: waiting for changes

#10515 1
  courses/free-courses-en.md
Labels: waiting for changes

#10765 fix grammar in code_of_conduct-id.md
  courses/free-courses-id.md
  docs/CODE_OF_CONDUCT-id.md
Labels: waiting for changes

#10967 Two New Flatter Playlist Added
  courses/free-courses-bn.md
Labels: waiting for changes

#10880 Fixing broken ui in case of "|"
  casts/free-podcasts-screencasts-en.md
  casts/free-podcasts-screencasts-fa_IR.md
  courses/free-courses-ar.md
  courses/free-courses-de.md
  courses/free-courses-hi.md
  courses/free-courses-ml.md
  courses/free-courses-si.md
  courses/free-courses-te.md
  courses/free-courses-ur.md
  more/problem-sets-competitive-programming.md
Labels: keep

#10740 added www. to the links and removed tracking parameters
  courses/free-courses-en.md
  courses/free-courses-hi.md
Labels: keep
