Repository EbookFoundation/free-programming-books, pull requests merged in 2023-10, with the labels that each got.

#9565 Add Python 3 Cheat Sheet from perso.limsi.fr (PDF)
  more/free-programming-cheatsheets.md
Labels: waiting for changes

#9591 (changes made) Update free-programming-books-langs.md
  books/free-programming-books-langs.md
Labels: waiting for changes

#9613 (Changes made) Added Node JS Playlists in Tamil.
  courses/free-courses-ta.md
Labels: waiting for changes

#9642 OPENS #9391 `(changes made)`
  books/free-programming-books-he.md
Labels: waiting for changes

#9658 Added a course resource. (Changes Made)
  courses/free-courses-en.md
Labels: waiting for changes

#9668 Add interactive tutorial page in German and Python course - changes made
  README.md
  more/free-programming-interactive-tutorials-de.md
Labels: waiting for changes

#9576 (Changes made) Added React JS Playlists in Tamil.
  courses/free-courses-ta.md
Labels: waiting for changes

#9632 (Changes made) Added Express JS playlists in Tamil.
  courses/free-courses-ta.md
Labels: waiting for changes

#9647 Add new books in Prompt Engineering (changes made)
  books/free-programming-books-subjects.md
Labels: waiting for changes

#9657 Issue No. #9522 : ADDED "Learn Python VIsiually" by Ivelin Demirov (changes made)
  books/free-programming-books-langs.md
Labels: waiting for changes

#9667 Added a new course(changes made)
  courses/free-courses-hi.md
Labels: waiting for changes

#9678 added java course and dsa course (changes made)
  courses/free-courses-ta.md
Labels: waiting for changes

#9684 Added AWS Course by Abhishek Veeramalla
  courses/free-courses-en.md
Labels: waiting for changes

#9696 Added a new networking course (changes made)
  courses/free-courses-en.md
Labels: waiting for changes

#9699 Added new book: Unix Programming Tools
  books/free-programming-books-langs.md
Labels: question

#9705 Added Resource (YouTube Video) for Spring Boot Master Class.( changes made )
  courses/free-courses-en.md
Labels: waiting for changes

#9706 Changes made
  courses/free-courses-hi.md
Labels: waiting for changes

#9707 check_urls=free-programming-books.md free-programming-books-en.md
  courses/free-courses-en.md
Labels: waiting for changes

#9713 Replaced obsolete course link under "courses" -> "DevOps" -> "Jenkins… (changes made)
  courses/free-courses-en.md
Labels: waiting for changes

#9720 Added two free ML courses in hindi (changes made)
  courses/free-courses-hi.md
Labels: waiting for changes

#9731 (changes made) - added python book
  books/free-programming-books-langs.md
Labels: waiting for changes

#9745 Added C++ category and a new Course (changes made)
  courses/free-courses-tr.md
Labels: waiting for changes

#9756 (changes made) Adding an Amazon DynamoDB Spanish eBook
  books/free-programming-books-es.md
Labels: waiting for changes

#9780 Deleted inactive/irrelevant links
  books/free-programming-books-bn.md
  books/free-programming-books-langs.md
  books/free-programming-books-pl.md
  books/free-programming-books-ru.md
  books/free-programming-books-zh.md
Labels: help wanted

#9771 Updated link for the Java Guide Book in the HE section
  books/free-programming-books-he.md
Labels: waiting for changes

#9805 (changes made) Add Linux Tutorial For Beginners in Hindi - M Prashant
  courses/free-courses-hi.md
Labels: waiting for changes

#9680 Update free-courses-id.md
  courses/free-courses-id.md
Labels: waiting for changes

#9719 Add aws solution architect resources (changes made)
  courses/free-courses-en.md
Labels: question, waiting for changes

#9619 added javascript hindi playlist
  courses/free-courses-hi.md
Labels: waiting for changes

#9673 Added 2 more courses in free-courses-hi.md
  courses/free-courses-hi.md
Labels: question

#9755 Improve german courses
  README.md
  courses/free-courses-de.md
  more/free-programming-playgrounds-de.md
Labels: waiting for changes

#9765 updating url addresses
  books/free-programming-books-ar.md
  books/free-programming-books-subjects.md
Labels: question

#9774 Update Networking section in free-courses-en.md
  courses/free-courses-en.md
Labels: waiting for changes

#9769 add Java Book Indonesia about Algorithm and Data Structure
  books/free-programming-books-id.md
Labels: waiting for changes

#9764 Add a new javascript course in bengali (changes made)
  courses/free-courses-bn.md
Labels: waiting for changes

#9747 (Changes made) Added C++ Object-Oriented Programming Course by CodeBeauty
  courses/free-courses-en.md
Labels: waiting for changes

#9760 (Changes made) Add Deep Reinforcement Learning Course from Hugging Face
  courses/free-courses-en.md
Labels: waiting for changes

#9762 Add C# course - Brazilian Portuguese (changes made)
  courses/free-courses-pt_BR.md
Labels: waiting for changes

#9792 Add Linux journey to free-programming-interactive-tutorials-en.md
  more/free-programming-interactive-tutorials-en.md
Labels: question

#9812 Improves Repo's Code of Conducts, Contributing, and How-to Indonesian Grammars (review assistance requested)
  docs/CODE_OF_CONDUCT-id.md
  docs/CONTRIBUTING-id.md
  docs/HOWTO-id.md
Labels: help wanted, :speaking_head: locale:id

#9818 NEW COURSES ARE ADDED.
  courses/free-courses-en.md
Labels: waiting for changes

#9826 Added: ReactJS, NodeJS,PHP Khode Academy
  courses/free-courses-km.md
Labels: waiting for changes

#9824 Add JavaScript Course
  courses/free-courses-en.md
Labels: waiting for changes

#9834 Add Servlet & JSP Tutorial Full Course - Telusko
  courses/free-courses-en.md
Labels: waiting for changes

#9703 Added Sorting Algorithms Course Playlist By Amulya's Academy(changes-made)
  courses/free-courses-en.md
Labels: waiting for changes

#9725 (changes made) Add More PT-BR courses
  courses/free-courses-pt_BR.md
Labels: waiting for changes

#9758 Add Svelte & SvelteKit Resources
  books/free-programming-books-langs.md
  courses/free-courses-en.md
  more/free-programming-interactive-tutorials-en.md
Labels: waiting for changes

#9816 Updated code-of-conduct-bn with native translation. (bangla review requested)
  docs/CODE_OF_CONDUCT-bn.md
Labels: help wanted, :speaking_head: locale:bn

#9844 Add two books in swedish
  books/free-programming-books-sv.md
Labels: waiting for changes

#9846 added a course, a cheatsheet, a tutorial (changes made)
  courses/free-courses-en.md
  more/free-programming-cheatsheets.md
  more/free-programming-interactive-tutorials-en.md
Labels: waiting for changes

#9847 (revised)Added 500 lines or less - OSS book
  books/free-programming-books-subjects.md
Labels: waiting for changes

#9877 add hebrew translation (hebrew reviewers requested)
  docs/HOWTO-he.md
  docs/README.md
Labels: help wanted, :speaking_head: locale:he

#9880 Added Python Django Course
  courses/free-courses-ta.md
Labels: :rocket: ready to merge

#9881 Update free-courses-hi.md (changes made)
  courses/free-courses-hi.md
Labels: waiting for changes

#9892 Added C++ course
  courses/free-courses-en.md
Labels: :rocket: ready to merge

#9894 Added Flexbox Froggy - CSS Game
  more/free-programming-playgrounds.md
Labels: :rocket: ready to merge

#9914 Updated Security section
  courses/free-courses-en.md
Labels: :rocket: ready to merge

#9902 feat: add algorithm book
  books/free-programming-books-subjects.md
Labels: :rocket: ready to merge

#9915 Bootstrap course
  courses/free-courses-en.md
Labels: :rocket: ready to merge

#9916 Add html course in EN
  courses/free-courses-en.md
Labels: :rocket: ready to merge

#9832 Add a Turkish Fortran book
  books/free-programming-books-tr.md
Labels: question

#9897 Update CONTRIBUTING.md
  docs/CONTRIBUTING.md
Labels: waiting for changes

#9588 Added New CheatSheet Of HTML
  more/free-programming-cheatsheets.md
Labels: waiting for changes

#9799 Added two free JavaScript courses in Hindi
  courses/free-courses-hi.md
Labels: waiting for changes

#9822 Added resource for Data Science e Machine Learning
  courses/free-courses-pt_BR.md
Labels: waiting for changes

#9852 add resource for kotlin
  books/free-programming-books-langs.md
Labels: waiting for changes

#9854 Added books in Tamil language
  books/free-programming-books-ta.md
Labels: waiting for changes

#9866 Update free-courses-hi.md
  courses/free-courses-hi.md
Labels: waiting for changes

#9874 C#
  books/free-programming-books-subjects.md
  casts/free-podcasts-screencasts-en.md
Labels: waiting for changes

#9887 Update free-programming-books-pt_BR.md with Architecture book
  books/free-programming-books-pt_BR.md
Labels: waiting for changes

#9863 Added DevOps, HTML&CSS and Linux resources to playground section
  more/free-programming-playgrounds.md
Labels: waiting for changes

#9920 free-courses-hi.md (adding resources)(changes made)
  courses/free-courses-hi.md
Labels: waiting for changes

#9937 new OS course (changes made again)
  courses/free-courses-en.md
Labels: waiting for changes

#9939 Added JavaScript book in Bengali (changes made)
  books/free-programming-books-bn.md
Labels: waiting for changes

#9988 Added New jQuery cheat sheet (Changes Made - Omitted `The`)
  more/free-programming-cheatsheets.md
Labels: waiting for changes

#9974 Added Data Structure Course
  courses/free-courses-hi.md
Labels: waiting for changes

#9985 Added books on computer architecture in Hindi. Created a topic in index for C which was missing.
  books/free-programming-books-hi.md
Labels: waiting for changes

#9970 [Fixes Issue #9959] C programming resource in bangla added
  courses/free-courses-bn.md
Labels: waiting for changes

#10002 Added 2 courses. One is Dynamic Programming by take U forward and another is Advanced Database Systems by CMU Database Group(revised)
  courses/free-courses-en.md
Labels: waiting for changes

#9971 Update free-courses-en.md
  courses/free-courses-en.md
Labels: waiting for changes

#9973 Update free-courses-en.md
  courses/free-courses-en.md
Labels: waiting for changes

#9969 Update free-courses-hi.md
  courses/free-courses-hi.md
Labels: waiting for changes

#9946 (COURSE ):Free Courses of language kannada added
  README.md
  courses/free-courses-kn.md
Labels: waiting for changes

#9951 Updated design pattern book by Saturngod to free-programming-books-my.md
  books/free-programming-books-my.md
Labels: waiting for changes

#9968 Adding Courses for Hindi Language
  courses/free-courses-hi.md
Labels: waiting for changes

#10032 Add React JS Bangla Tutorial
  courses/free-courses-bn.md
Labels: waiting for changes

#10033 Pro Coder Docker Playlist Added
  courses/free-courses-bn.md
Labels: waiting for changes

#9956 Added AI course
  courses/free-courses-en.md
Labels: waiting for changes

#9984 Added Oracle Database Book
  books/free-programming-books-langs.md
Labels: waiting for changes

#10013 Add Bangla WordPress Plugin Development Tutorial Playlist
  courses/free-courses-bn.md
Labels: waiting for changes

#10016 Add English Advanced WordPress Theme Development Course
  courses/free-courses-en.md
Labels: waiting for changes

#10021 Add PHP OOP Tutorial in Hindi
  courses/free-courses-hi.md
Labels: question

#9955 Added Android course
  courses/free-courses-en.md
Labels: waiting for changes

#9967 Added: km code of conduct (khmer review requested)
  docs/CODE_OF_CONDUCT-km.md
  docs/README.md
Labels: help wanted, :speaking_head: locale:km

#10019 📚 Added: MongoDB (NoSQL) 'Introduction to MongoDB' by MongoDB University
  courses/free-courses-en.md
Labels: waiting for changes

#10045 changes made
  more/problem-sets-competitive-programming.md
Labels: question, waiting for changes

#9991 Adding React course
  courses/free-courses-en.md
Labels: waiting for changes

#10072 Add PHP tutorial for beginners in english
  courses/free-courses-en.md
Labels: waiting for changes

#10017 Add WordPress Theme Development Complete Course Tutorial in Hindi
  courses/free-courses-hi.md
Labels: question

#9972 Update free-courses-hi.md
  courses/free-courses-hi.md
Labels: waiting for changes

#10058 Added a Maths for CP course.
  courses/free-courses-hi.md
Labels: waiting for changes

#10009 React JS Free Course Added for Complete Beginners
  courses/free-courses-hi.md
Labels: waiting for changes

#10035 python flask course added
  courses/free-courses-ta.md
Labels: waiting for changes

#10082 Update free-courses-en.md
  courses/free-courses-en.md
Labels: waiting for changes

#10130 Add Tailwind CSS Tutorials in Bangla
  courses/free-courses-bn.md
Labels: waiting for changes

#10061 Added redux course in hindi and updated heading of ReactNative courses
  courses/free-courses-hi.md
Labels: waiting for changes

#10123 Full Python Tutorial in Hindi by "Great Learning"
  courses/free-courses-hi.md
Labels: waiting for changes

#9884 Added courses on Cuda and Fortran
  courses/free-courses-en.md
Labels: waiting for changes

#10116 added html cheatsheet
  more/free-programming-cheatsheets.md
Labels: waiting for changes

#10119 added Nepali courses- php and javascript
  courses/free-courses-ne.md
Labels: waiting for changes

#10065 Update free-courses-hi.md
  courses/free-courses-hi.md
Labels: waiting for changes

#10157 Fast Api Course tamil added
  courses/free-courses-ta.md
Labels: waiting for changes

#10156 Update free-courses-en.md
  courses/free-courses-en.md
Labels: waiting for changes

#10144 Add spanish mongoDB course (changes made)
  courses/free-courses-es.md
Labels: waiting for changes

#10136 Adds Learn4Elixir content
  books/free-programming-books-pt_BR.md
Labels: question

#10176 add: course - html udemy (id)
  courses/free-courses-id.md
Labels: waiting for changes

#10132 Add openstack
  books/free-programming-books-subjects.md
Labels: waiting for changes

#10169 Added Golang Gin Web Framework to free-programming-books-langs.md
  books/free-programming-books-langs.md
Labels: waiting for changes

#10152 Add NLP Course from Hugging Face
  courses/free-courses-en.md
Labels: waiting for changes

#10212 add first portuguese Next.js course
  books/free-programming-books-pt_BR.md
Labels: :rocket: ready to merge

#10104 removed bad link (data on site deleted)
  books/free-programming-books-ar.md
Labels: waiting for changes

#10200 Add New PHP Playlist
  courses/free-courses-bn.md
Labels: waiting for changes

#10196 Add learning csharp ebook to books
  books/free-programming-books-langs.md
Labels: waiting for changes

#10128 Courses on Computer Networks and Distributed Computing added in the Malayalam language section
  courses/free-courses-ml.md
Labels: waiting for changes

#9749 Added new advanced course for Next.js
  courses/free-courses-en.md
Labels: waiting for changes

#10204 Fix translation error (review requested)
  docs/CONTRIBUTING-zh.md
Labels: help wanted, :speaking_head: locale:zh

#10234 Update free-courses-en.md
  courses/free-courses-en.md
Labels: waiting for changes

#10189 Css list
  courses/free-courses-bn.md
Labels: waiting for changes

#10211 (COURSE): Added the marathi langauge courses markdown file
  README.md
  courses/free-courses-mr.md
Labels: waiting for changes

#10170 Update free-programming-books-langs.md
  books/free-programming-books-langs.md
Labels: waiting for changes

#10252 Add Portuguese-language Artificial Intelligence Book
  books/free-programming-books-pt_BR.md
Labels: :rocket: ready to merge

#10255 Update free-courses-hi.md
  courses/free-courses-hi.md
Labels: :rocket: ready to merge

#10276 Added a Three.js Course
  courses/free-courses-en.md
Labels: :rocket: ready to merge

#10278 Added a System Design Course (Updated)
  courses/free-courses-en.md
Labels: :rocket: ready to merge

#10287 docs: fix typos in books/free-programming-books-subjects.md
  books/free-programming-books-subjects.md
Labels: :rocket: ready to merge

#10288 docs: fix typos in courses/free-courses-en.md
  courses/free-courses-en.md
Labels: :rocket: ready to merge

#10304 Update free-courses-hi.md
  courses/free-courses-hi.md
Labels: :rocket: ready to merge

#10161 Update free-programming-books-subjects.md
  books/free-programming-books-subjects.md
Labels: waiting for changes

#10310 Full Stack Development in Ruby on Rails - Hindi
  courses/free-courses-hi.md
Labels: :rocket: ready to merge

#10223 Added Web Development course
  courses/free-courses-en.md
Labels: changes made

#10172 Added Code of Conduct in Sinhala language (review requested)
  docs/CODE_OF_CONDUCT-si.md
  docs/README.md
Labels: waiting for changes, help wanted, :speaking_head: locale:si

#10030 Translating ZH for Contributing document (zh review requested)
  docs/CONTRIBUTING-zh.md
Labels: help wanted, :speaking_head: locale:zh

#9802 remove javatpoint links? fixes #9801
  more/free-programming-interactive-tutorials-en.md
Labels: :busts_in_silhouette: discussion

#10295 new course added
  courses/free-courses-en.md
Labels: waiting for changes

#10003 Fixed typo CODE_OF_CONDUCT-ko.md (korean review requested)
  docs/CODE_OF_CONDUCT-ko.md
Labels: help wanted, :speaking_head: locale:ko

#10279 add: 2 new courses
  courses/free-courses-en.md
Labels: waiting for changes

#10352 Remove Codecademy Courses From The Book List
  books/free-programming-books-langs.md
Labels: :rocket: ready to merge

#10353 Added Ruby Course from CodeCademy and improve the repos
  courses/free-courses-en.md
Labels: :rocket: ready to merge

#10364 Added Linked List by Pepcoding
  courses/free-courses-hi.md
Labels: :rocket: ready to merge

#10366 remove invalid links for flutter and python books (id)
  books/free-programming-books-id.md
Labels: :rocket: ready to merge
