Repository EbookFoundation/free-programming-books, pull requests merged in 2024-01, with the labels that each got.

#10393 Enhance Indonesian translation (review assistance requested)
  docs/CONTRIBUTING-id.md
  docs/HOWTO-id.md
Labels: help wanted, stale, :speaking_head: locale:id

#11043 Bump actions/upload-artifact from 3 to 4
  .github/workflows/check-urls.yml
  .github/workflows/fpb-lint.yml
Labels: 🔗 dependencies:github-actions

#11054 add link to MoonMath book (zk-SNARKs, zero-knowledge proofs)
  books/free-programming-books-subjects.md
Labels: waiting for changes
