Repository EbookFoundation/free-programming-books, pull requests merged in 2024-10, with the labels that each got.

#11275 Add OS hindi course
  courses/free-courses-hi.md
Labels: :rocket: ready to merge

#11314 chore: Added new Rust Hindi Course
  courses/free-courses-hi.md
Labels: :rocket: ready to merge

#11318 Update free-courses-en.md
  courses/free-courses-en.md
Labels: :rocket: ready to merge

#11281 Adding Prompt Engineering Hindi course to the courses section
  courses/free-courses-hi.md
Labels: waiting for changes

#11322 Update free-programming-books-bn.md
  books/free-programming-books-bn.md
Labels: :rocket: ready to merge

#11307 book on linear algebra and multidimensional geometry added
  books/free-programming-books-subjects.md
Labels: waiting for changes

#11315 chore: Added Nextjs 14 Course
  courses/free-courses-en.md
Labels: waiting for changes

#11319 Next js course by hitesh choudhary
  courses/free-courses-hi.md
Labels: waiting for changes

#11330 Added "Foundations of Python Programming" Book
  more/free-programming-interactive-tutorials-en.md
Labels: waiting for changes

#11345 C++ course by hitesh choudhary in hindi
  courses/free-courses-hi.md
Labels: waiting for changes

#11340 Update free-courses-hi.md
  courses/free-courses-hi.md
Labels: waiting for changes

#11346 Update free-courses-en.md with Learn Blockchain & Solidity Development Full Course 2024
  courses/free-courses-en.md
Labels: waiting for changes

#11375 Add "Total TypeScript: Essentials" to TypeScript books
  books/free-programming-books-langs.md
Labels: :rocket: ready to merge

#11380 Added Deep Learning Course in free-courses-en.md
  courses/free-courses-en.md
Labels: :rocket: ready to merge

#11385 Add 'Introduction to Linux' to free-programming-books-langs.md
  books/free-programming-books-langs.md
Labels: :rocket: ready to merge

#11378 Update free-programming-books-subjects.md
  books/free-programming-books-subjects.md
Labels: :rocket: ready to merge

#11377 HTML course by Hitesh Choudhary in Hindi language
  courses/free-courses-hi.md
Labels: :rocket: ready to merge

#11387 Adds cheatsheet for AI Terminologies (Changes Made)
  more/free-programming-cheatsheets.md
Labels: waiting for changes

#11392 ebooks: add new indonesia's programming book links
  books/free-programming-books-id.md
Labels: question

#11301 Updated broken links, Removed unavailable and other language links from Bangla resource list
  courses/free-courses-bn.md
Labels: waiting for changes

#11388 Add CUDA Course (changes made)
  courses/free-courses-en.md
Labels: waiting for changes

#11384 Adding free resource (course) for Artificial Intelligence.
  courses/free-courses-en.md
Labels: question

#11393 Add Eloquent JavaScript (1er, 2do, 3ra, 4ta Edicion)
  books/free-programming-books-es.md
Labels: waiting for changes

#11391 Added OpenCV Tutorial by WsCube Tech (changes made)
  courses/free-courses-hi.md
Labels: :rocket: ready to merge

#11397 feat(Courses): Add Full HTML And Tailwind CSS Course (Hindi) with proper url (changes made)
  courses/free-courses-hi.md
Labels: waiting for changes

#11396 feat(Courses): Add Git and GitHub Course (Hindi) with proper url (changes made)
  courses/free-courses-hi.md
Labels: waiting for changes

#11389 Add HTML Course (changes made)
  courses/free-courses-hi.md
Labels: waiting for changes

#11299 Pull Request: Add Hindi Translation for CONTRIBUTING.md (Changes Made)
  docs/CONTRIBUTING-hi.md
  docs/README.md
Labels: :speaking_head: translations

#11419 Add license notes on Embedded System and Operating system resources
  books/free-programming-books-subjects.md
Labels: waiting for changes

#11418 Update free-courses-hi.md
  courses/free-courses-hi.md
Labels: waiting for changes

#11394 Added gsap JavaScript library course in Hindi language
  courses/free-courses-hi.md
Labels: waiting for changes

#11423 Added Next.js course from offical site--Hacktoberfest
  courses/free-courses-en.md
Labels: waiting for changes

#11452 Add Databases Course in free-courses-en.md (Changes made)
  courses/free-courses-en.md
Labels: waiting for changes

#11449 3 Books License Added
  books/free-programming-books-langs.md
Labels: waiting for changes

#11440 Build a Bank App - Added Node.js Course By Ugwu Somto
  courses/free-courses-en.md
Labels: waiting for changes

#11477 Added author of the course
  courses/free-courses-en.md
Labels: :rocket: ready to merge

#11496 Added a C Programming Course in free-courses-hi.md
  courses/free-courses-hi.md
Labels: :rocket: ready to merge

#11470 Added golang course by codergyan
  courses/free-courses-hi.md
Labels: :rocket: ready to merge

#11485 Added "Artificial Intelligence, 3rd Edition" Book by Patrick Winston
  books/free-programming-books-subjects.md
Labels: waiting for changes

#11495 Add book "Learn JavaScript" by Suman Kumar
  books/free-programming-books-es.md
  books/free-programming-books-fr.md
  books/free-programming-books-hi.md
  books/free-programming-books-id.md
  books/free-programming-books-langs.md
  books/free-programming-books-tr.md
Labels: waiting for changes

#11486 Fix the brackets surrounding the link from full-width to half-width(ja)
  docs/CODE_OF_CONDUCT-ja.md
Labels: :rocket: ready to merge, changes made

#11487 Fix missing backticks(ja)
  docs/HOWTO-ja.md
Labels: :rocket: ready to merge, changes made

#11476 Added a course for solidity in Hindi
  courses/free-courses-hi.md
Labels: waiting for changes

#11494 Add Comprehensive Free Resources for Algorithms and System Design.
  courses/free-courses-ur.md
  more/problem-sets-competitive-programming.md
Labels: waiting for changes

#11481 Add HTML course to Vietnamese course list
  courses/free-courses-vi.md
Labels: waiting for changes

#11521 Add Typescript course by Hitesh Choudhary
  courses/free-courses-en.md
Labels: :rocket: ready to merge

#11524 add practice-linux-commands-free-course to courses/free-courses-en.md
  more/free-programming-interactive-tutorials-en.md
Labels: question

#11479 Added license notes to 3 books and added type of book (pdf) for one
  books/free-programming-books-langs.md
Labels: waiting for changes

#11544 Removed English Course from Hindi File
  courses/free-courses-hi.md
Labels: question

#11547 feat: add new indonesia's free ebooks
  books/free-programming-books-id.md
Labels: waiting for changes

#11536 Update free-courses-en.md
  courses/free-courses-en.md
Labels: waiting for changes

#11548 Added a Compiler Design Course in Hindi
  courses/free-courses-hi.md
Labels: waiting for changes

#11533 Add LabEx to list of MOOC
  courses/free-courses-en.md
Labels: waiting for changes

#11455 Added database courses by Scaler and Simplilearn
  courses/free-courses-en.md
  more/free-programming-interactive-tutorials-en.md
Labels: waiting for changes

#11374 [Changes made] Update free-courses-en.md
  courses/free-courses-en.md
Labels: waiting for changes

#11565 [NEW COURSE] Added Material UI courses
  courses/free-courses-hi.md
Labels: waiting for changes

#11568 Added Elisp Programming Book
  books/free-programming-books-langs.md
Labels: waiting for changes

#11540 added license
  books/free-programming-books-subjects.md
Labels: waiting for changes

#11572 Fix case. Php < PHP
  books/free-programming-books-hi.md
Labels: waiting for changes

#11575 Update free-programming-books-langs.md
  books/free-programming-books-langs.md
Labels: waiting for changes

#11580 Add PHP - Yii Framework - e-book (PDF)
  books/free-programming-books-id.md
  books/free-programming-books-langs.md
Labels: waiting for changes

#11558 Added a free course of Bootstrap by Scrimba
  courses/free-courses-en.md
Labels: question

#11591 Added new embedded section in polish language
  courses/free-courses-pl.md
Labels: waiting for changes

#11579 Add Guide to NumPY
  books/free-programming-books-langs.md
Labels: waiting for changes

#11589 Update free-courses-en.md
  courses/free-courses-en.md
Labels: waiting for changes

#11583 Add Scikit Learn Choosing the Right Estimators cheatsheet
  books/free-programming-books-subjects.md
Labels: waiting for changes

#11587 feat: add vim resources
  courses/free-courses-en.md
Labels: waiting for changes

#11615 Added ReactJS course by Anurag Singh
  courses/free-courses-hi.md
Labels: waiting for changes

#11606 Add new Arduino course in pl lang
  courses/free-courses-pl.md
Labels: question

#11634 Add NestJS section and 2 free video courses
  courses/free-courses-en.md
Labels: waiting for changes

#11633 Added Python book resource
  books/free-programming-books-langs.md
Labels: waiting for changes

#11641 Build a Blockchain from Scratch in Go with gRPC
  books/free-programming-books-subjects.md
Labels: waiting for changes

#11654 Update for ded links - kn. and uk.
  courses/free-courses-kn.md
  courses/free-courses-uk.md
Labels: :rocket: ready to merge

#11650 [Updated] Kotlin Course
  courses/free-courses-en.md
Labels: waiting for changes

#11646 [PR] Add DevOps and Software Testing Essential books in Tamil
  books/free-programming-books-ta.md
Labels: waiting for changes

#11658 Add License Information to 'Open Data Structures (In C++)'
  books/free-programming-books-langs.md
Labels: waiting for changes

#11653 Adding (CC BY-NC-ND) license
  books/free-programming-books-pt_BR.md
Labels: waiting for changes

#11663 Added Linux books in Tamil language
  books/free-programming-books-ta.md
Labels: waiting for changes

#11645 Update free-programming-books-langs.md
  books/free-programming-books-langs.md
Labels: waiting for changes

#11674 Update free-courses-zh.md
  courses/free-courses-zh.md
Labels: waiting for changes

#11676 bangla programing books added
  books/free-programming-books-bn.md
Labels: waiting for changes

#11692 Update free-courses-te.md
  courses/free-courses-te.md
Labels: waiting for changes

#11693 Added Design and Analysis of Algorithms course by THE GATEHUB to free-courses-hi.md
  courses/free-courses-hi.md
Labels: waiting for changes

#11697 Added Nextjs Resources in free-courses-ur.md
  courses/free-courses-ur.md
Labels: :rocket: ready to merge

#11695 Added Complete NodeJS + ExpressJS + MongoDB Course by Complete Coding by Prashant Sir to free-courses-hi.md
  courses/free-courses-hi.md
Labels: waiting for changes

#11707 Added English book (Learn Java for FTC)
  books/free-programming-books-langs.md
Labels: waiting for changes

#11710 Fixed Existing Tamil Language Books file
  books/free-programming-books-ta.md
Labels: waiting for changes

#11704 Adding git course in PT-BR section
  courses/free-courses-pt_BR.md
Labels: waiting for changes

#11731 Feature: Add Backend Essentials Section with Workshops
  courses/free-courses-bn.md
Labels: waiting for changes

#11686 Added ruby, ruby on rails and rust hindi tutorials in free-courses-hindi.md (request review from urdu speaker)
  courses/free-courses-hi.md
Labels: question, waiting for changes

#11729 Added a free Course in free-courses-hi.md
  courses/free-courses-hi.md
Labels: waiting for changes
