Repository EbookFoundation/free-programming-books, pull requests merged in 2025-10, with the labels that each got.

#12014 Remove broken PHP links
  books/free-programming-books-langs.md
Labels: :rocket: ready to merge

#12003 Add new book to free-programming-books-subjects.md for the index of Computer Science.
  books/free-programming-books-subjects.md
Labels: waiting for changes

#12051 Remove outdated links in Korean course list
  courses/free-courses-ko.md
Labels: :rocket: ready to merge

#12063 Add Rego Playground to Playgrounds
  more/free-programming-playgrounds.md
Labels: waiting for changes

#12081 Update free-programming-books-langs.md
  books/free-programming-books-langs.md
Labels: waiting for changes

#12107 Data Structures by Nargish Gupta to Hindi Data Structures courses
  courses/free-courses-hi.md
Labels: :rocket: ready to merge

#12062 feat: add new bash course amd remove notfound books
  books/free-programming-books-pt_BR.md
  courses/free-courses-pt_BR.md
Labels: :rocket: ready to merge

#12082 Added new free Prompt Engineering resources
  books/free-programming-books-bg.md
  books/free-programming-books-subjects.md
Labels: waiting for changes

#12090 The YouTube channel "Formation Video" became "EvoluNoob"
  courses/free-courses-fr.md
Labels: waiting for changes

#12108 check_urls=free-programming-books-pt_BR.md
  courses/free-courses-pt_BR.md
Labels: waiting for changes

#12140 Add CoursesFree Javascript pt-br
  courses/free-courses-pt_BR.md
Labels: :rocket: ready to merge

#12153 Add: Introduction to Data Science with Python
  courses/free-courses-en.md
Labels: :rocket: ready to merge

#12158 Add Italian base course about Spring Boot
  courses/free-courses-it.md
Labels: :rocket: ready to merge

#12132 Add Courses Free Java And Spring Boot pt-br
  courses/free-courses-pt_BR.md
Labels: waiting for changes

#12135 Add Free Courses Go pt-br
  courses/free-courses-pt_BR.md
Labels: waiting for changes

#12133 Added Statistics and Machine Learning in R course. From StatQuest by Josh Starmer
  courses/free-courses-en.md
Labels: waiting for changes

#12114 add Google SRE books
  books/free-programming-books-subjects.md
Labels: waiting for changes

#12074 add FastAPI — The Blue Book to Python books
  books/free-programming-books-langs.md
Labels: waiting for changes

#12111 Update free-programming-books-subjects.md
  books/free-programming-books-subjects.md
Labels: waiting for changes

#12004 docs: add Tamil translation for CONTRIBUTING.md (Tamil review needed)
  docs/CONTRIBUTING-ta.md
  docs/README.md
Labels: :eyes: Needs Review, :speaking_head: locale:ta

#12179 Added CODE_OF_CONDUCT-ta.md in docs folder
  docs/CODE_OF_CONDUCT-ta.md
  docs/README.md
Labels: waiting for changes, :eyes: Needs Review

#12195 Python course in Spanish for beginners
  courses/free-courses-es.md
Labels: waiting for changes

#12268 Add Greek (el) C++ book: "Προγραμματισμός με τη γλώσσα C++"
  books/free-programming-books-el.md
Labels: :rocket: ready to merge, :speaking_head: locale:el

#12206 docs: add interactive tutorials for Redux, LaTeX, PHP, PostgreSQL, an…
  books/free-programming-books-langs.md
  more/free-programming-interactive-tutorials-en.md
Labels: waiting for changes

#12215 Update free-courses-hi.md
  courses/free-courses-hi.md
Labels: waiting for changes

#12256 Improve html/css courses fr section
  courses/free-courses-fr.md
Labels: waiting for changes

#12273 Update free-programming-books-langs.md
  books/free-programming-books-langs.md
Labels: waiting for changes

#12271 feat: add RO python course
  README.md
  courses/free-courses-ro.md
Labels: waiting for changes

#12272 Update free-programming-books-hi.md
  books/free-programming-books-hi.md
Labels: waiting for changes

#12176 add-free-courses-id
  courses/free-courses-id.md
Labels: waiting for changes

#12054 Add Persian WordPress tutorial to free-courses-fa_IR.md
  courses/free-courses-fa_IR.md
Labels: waiting for changes

#12289 Removed WORD file Network Security by OpenLearn
  books/free-programming-books-subjects.md
Labels: waiting for changes

#12339 Fixed and replaced broken links(3)
  books/free-programming-books-langs.md
Labels: waiting for changes
